#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

python manage.py rename_app users account
python manage.py migrate --noinput

python manage.py install_askanna_create_project
python manage.py install_default_settings

echo "Starting Django server"
python -Wd manage.py runserver_plus 0.0.0.0:8000
