# Generated by Django 3.2.16 on 2022-11-03 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='short_uuid',
            new_name='suuid',
        ),
        migrations.RenameField(
            model_name='passwordresetlog',
            old_name='short_uuid',
            new_name='suuid',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='short_uuid',
            new_name='suuid',
        ),
    ]
