# Generated by Django 2.2.8 on 2020-04-09 05:30

import uuid

from django.db import migrations

from core.utils import GoogleTokenGenerator, bx_decode


def gen_uuid(apps, schema_editor):
    User = apps.get_model("users", "User")
    for row in User.objects.all():
        row.uuid = uuid.uuid4()
        google_token = GoogleTokenGenerator()
        row.short_uuid = google_token.create_token(key="", uuid=row.uuid)
        row.save(update_fields=["uuid", "short_uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20200409_0525"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
