# Generated by Django 2.2.8 on 2020-05-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200417_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='object_uuid',
            field=models.UUIDField(db_index=True),
        ),
    ]
