# Generated by Django 2.2.8 on 2020-08-25 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('users', '0006_auto_20200519_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='role',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
