# Generated by Django 2.2.8 on 2020-09-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_membership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Job title'),
        ),
    ]
