# Generated by Django 2.2.8 on 2020-08-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_membership_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('WM', 'Member'), ('WA', 'Admin')], max_length=2),
        ),
    ]
