# Generated by Django 2.2.8 on 2020-09-16 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200910_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('membership_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.Membership')),
            ],
            options={
                'abstract': False,
            },
            bases=('users.membership',),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('WM', 'member'), ('WA', 'admin')], default='WM', max_length=2),
        ),
    ]
