# Generated by Django 2.2.8 on 2020-08-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200826_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('WM', 'Member'), ('WA', 'Admin')], default='WM_MEMBER', max_length=2),
        ),
    ]
