# Generated by Django 2.2.8 on 2020-09-16 10:17

from django.db import migrations

def create_profile(apps, schema_editor):
    UserProfile = apps.get_model('users', 'UserProfile')
    Membership = apps.get_model('users', 'Membership')
    for membership in Membership.objects.all():
        userprofile = UserProfile()
        userprofile.membership_ptr = membership
        userprofile.save_base(raw=True)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200916_0900'),
    ]

    operations = [
        migrations.RunPython(create_profile, migrations.RunPython.noop),
    ]
