# Generated by Django 2.2.8 on 2020-09-29 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200923_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='expiry_date',
        ),
    ]
