# Generated by Django 2.2.8 on 2020-11-24 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20201028_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='front_end_url',
            field=models.URLField(),
        ),
    ]
