# Generated by Django 2.2.8 on 2020-12-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_passwordresetlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='front_end_domain',
            field=models.CharField(default=None, max_length=1024, null=True),
        ),
    ]
