# Generated by Django 2.2.8 on 2020-12-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_front_end_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='name',
        ),
        migrations.AddField(
            model_name='membership',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name of User'),
        ),
    ]
