# Generated by Django 2.2.24 on 2021-09-01 15:15

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    """
    For existing Memberships we don't have a global profile,
    these profiles should not have the 'use_global_profile' turned on
    """
    Membership = apps.get_model("users", "Membership")

    for obj in Membership.objects.all():
        if obj.name or obj.job_title:
            # only set to use_global_profile when the name or job_title was never changed
            obj.use_global_profile = False
            obj.save(update_fields=["use_global_profile"])


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_auto_20201222_1508"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="job_title",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Job title"
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="use_global_profile",
            field=models.BooleanField(
                default=True,
                help_text="Use information from the global AskAnna profile",
                verbose_name="Use global profile",
            ),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
