# Generated by Django 2.2.24 on 2021-09-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_global_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('WV', 'viewer'), ('WM', 'member'), ('WA', 'admin')], default='WM', max_length=2),
        ),
        migrations.AlterField(
            model_name='membership',
            name='use_global_profile',
            field=models.BooleanField(default=True, help_text='Use information from the global AskAnna profile', verbose_name='Use AskAnna profile'),
        ),
    ]
