# Generated by Django 3.1.14 on 2022-08-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20220823_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetlog',
            name='meta',
            field=models.JSONField(default=None, null=True),
        ),
    ]
