# Generated by Django 4.2.8 on 2024-01-04 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0002_update_project_created_by"),
        ("variable", "0001_initial_20230414"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variable",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="variables", to="project.project"
            ),
        ),
    ]
