# Generated by Django 3.2.18 on 2023-02-28 11:26

from django.db import migrations

import core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('variable', '0003_add_at_suffix_to_datetime_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='created_at',
            field=core.fields.CreationDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='modified_at',
            field=core.fields.ModificationDateTimeField(auto_now=True),
        ),
    ]
