# Generated by Django 2.2.8 on 2019-12-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DummyFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadedfile', models.FileField(blank=True, default='', upload_to='')),
            ],
        ),
    ]
