# Generated by Django 3.2.15 on 2022-09-20 14:59

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("run", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Log",
                    fields=[
                        (
                            "created",
                            django_extensions.db.fields.CreationDateTimeField(
                                auto_now_add=True, verbose_name="created"
                            ),
                        ),
                        (
                            "modified",
                            django_extensions.db.fields.ModificationDateTimeField(
                                auto_now=True, verbose_name="modified"
                            ),
                        ),
                        ("deleted", models.DateTimeField(blank=True, null=True)),
                        (
                            "uuid",
                            models.UUIDField(
                                db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                            ),
                        ),
                        ("short_uuid", models.CharField(blank=True, max_length=32, unique=True)),
                        ("jobdef", models.UUIDField(blank=True, editable=False, null=True)),
                        ("exit_code", models.IntegerField(default=0)),
                        ("stdout", models.JSONField(blank=True, null=True)),
                        (
                            "jobrun",
                            models.OneToOneField(
                                on_delete=django.db.models.deletion.CASCADE, related_name="output", to="run.run"
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Run Log",
                        "verbose_name_plural": "Run Logs",
                        "ordering": ["-created"],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
