# Generated by Django 3.2.15 on 2022-09-20 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0002_log'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='run',
            options={'ordering': ['-created']},
        ),
    ]
