# Generated by Django 3.2.15 on 2022-09-23 08:36

import core.models
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("run", "0005_alter_result_options"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="RunArtifact",
                    fields=[
                        (
                            "created",
                            django_extensions.db.fields.CreationDateTimeField(
                                auto_now_add=True, verbose_name="created"
                            ),
                        ),
                        (
                            "modified",
                            django_extensions.db.fields.ModificationDateTimeField(
                                auto_now=True, verbose_name="modified"
                            ),
                        ),
                        ("deleted", models.DateTimeField(blank=True, null=True)),
                        (
                            "uuid",
                            models.UUIDField(
                                db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                            ),
                        ),
                        ("short_uuid", models.CharField(blank=True, max_length=32, unique=True)),
                        ("size", models.PositiveIntegerField(default=0, editable=False)),
                        ("count_dir", models.PositiveIntegerField(default=0, editable=False)),
                        ("count_files", models.PositiveIntegerField(default=0, editable=False)),
                        (
                            "jobrun",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE, related_name="artifact", to="run.run"
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Run Artifact",
                        "verbose_name_plural": "Run Artifacts",
                        "ordering": ["-created"],
                    },
                    bases=(core.models.ArtifactModelMixin, models.Model),
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="ChunkedRunArtifactPart",
                    fields=[
                        (
                            "created",
                            django_extensions.db.fields.CreationDateTimeField(
                                auto_now_add=True, verbose_name="created"
                            ),
                        ),
                        (
                            "modified",
                            django_extensions.db.fields.ModificationDateTimeField(
                                auto_now=True, verbose_name="modified"
                            ),
                        ),
                        ("deleted", models.DateTimeField(blank=True, null=True)),
                        (
                            "uuid",
                            models.UUIDField(
                                db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                            ),
                        ),
                        ("short_uuid", models.CharField(blank=True, max_length=32, unique=True)),
                        ("filename", models.CharField(max_length=500)),
                        ("size", models.IntegerField(help_text="Size of this artifactchunk")),
                        ("file_no", models.IntegerField()),
                        ("is_last", models.BooleanField(default=False)),
                        (
                            "artifact",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                to="run.runartifact",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Run Artifact Chunk",
                        "verbose_name_plural": "Run Artifacts Chunks",
                        "ordering": ["-created"],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
