# Generated by Django 3.2.15 on 2022-09-27 11:43

import core.models
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("run", "0007_alter_runartifact_table"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="RunMetric",
                    fields=[
                        (
                            "created",
                            django_extensions.db.fields.CreationDateTimeField(
                                auto_now_add=True, verbose_name="created"
                            ),
                        ),
                        (
                            "modified",
                            django_extensions.db.fields.ModificationDateTimeField(
                                auto_now=True, verbose_name="modified"
                            ),
                        ),
                        ("deleted", models.DateTimeField(blank=True, null=True)),
                        (
                            "uuid",
                            models.UUIDField(
                                db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                            ),
                        ),
                        (
                            "count",
                            models.PositiveIntegerField(default=0, editable=False, help_text="Count of metrics"),
                        ),
                        (
                            "size",
                            models.PositiveIntegerField(
                                default=0, editable=False, help_text="File size of metrics JSON"
                            ),
                        ),
                        (
                            "metric_names",
                            models.JSONField(
                                blank=True,
                                default=None,
                                editable=False,
                                help_text="Unique metric names and data type for metric",
                                null=True,
                            ),
                        ),
                        (
                            "label_names",
                            models.JSONField(
                                blank=True,
                                default=None,
                                editable=False,
                                help_text="Unique metric label names and data type for metric label",
                                null=True,
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Run Metric",
                        "verbose_name_plural": "Run Metrics",
                        "db_table": "run_metric",
                        "ordering": ["-created"],
                    },
                    bases=(core.models.ArtifactModelMixin, models.Model),
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="RunMetricRow",
                    fields=[
                        (
                            "modified",
                            django_extensions.db.fields.ModificationDateTimeField(
                                auto_now=True, verbose_name="modified"
                            ),
                        ),
                        ("deleted", models.DateTimeField(blank=True, null=True)),
                        (
                            "uuid",
                            models.UUIDField(
                                db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                            ),
                        ),
                        ("short_uuid", models.CharField(blank=True, max_length=32, unique=True)),
                        ("project_suuid", models.CharField(db_index=True, editable=False, max_length=32)),
                        ("job_suuid", models.CharField(db_index=True, editable=False, max_length=32)),
                        ("run_suuid", models.CharField(db_index=True, editable=False, max_length=32)),
                        (
                            "metric",
                            models.JSONField(
                                default=None,
                                editable=False,
                                help_text="JSON field as list with multiple objects which are metrics, but we limit to one",
                            ),
                        ),
                        (
                            "label",
                            models.JSONField(
                                default=None,
                                editable=False,
                                help_text="JSON field as list with multiple objects which are labels",
                            ),
                        ),
                        ("created", models.DateTimeField(default=django.utils.timezone.now)),
                    ],
                    options={
                        "verbose_name": "Run Metric Row",
                        "verbose_name_plural": "Run Metric Rows",
                        "db_table": "run_metricrow",
                        "ordering": ["-created"],
                    },
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="RunVariable",
                    fields=[
                        (
                            "created",
                            django_extensions.db.fields.CreationDateTimeField(
                                auto_now_add=True, verbose_name="created"
                            ),
                        ),
                        (
                            "modified",
                            django_extensions.db.fields.ModificationDateTimeField(
                                auto_now=True, verbose_name="modified"
                            ),
                        ),
                        ("deleted", models.DateTimeField(blank=True, null=True)),
                        (
                            "uuid",
                            models.UUIDField(
                                db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                            ),
                        ),
                        (
                            "count",
                            models.PositiveIntegerField(default=0, editable=False, help_text="Count of variables"),
                        ),
                        (
                            "size",
                            models.PositiveIntegerField(
                                default=0, editable=False, help_text="File size of variables JSON"
                            ),
                        ),
                        (
                            "variable_names",
                            models.JSONField(
                                blank=True,
                                default=None,
                                editable=False,
                                help_text="Unique variable names and data type for variable",
                                null=True,
                            ),
                        ),
                        (
                            "label_names",
                            models.JSONField(
                                blank=True,
                                default=None,
                                editable=False,
                                help_text="Unique variable label names and data type for variable label",
                                null=True,
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Run Variable",
                        "verbose_name_plural": "Run Variables",
                        "db_table": "run_variable",
                        "ordering": ["-created"],
                    },
                    bases=(core.models.ArtifactModelMixin, models.Model),
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="RunVariableRow",
                    fields=[
                        (
                            "modified",
                            django_extensions.db.fields.ModificationDateTimeField(
                                auto_now=True, verbose_name="modified"
                            ),
                        ),
                        ("deleted", models.DateTimeField(blank=True, null=True)),
                        (
                            "uuid",
                            models.UUIDField(
                                db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                            ),
                        ),
                        ("short_uuid", models.CharField(blank=True, max_length=32, unique=True)),
                        ("project_suuid", models.CharField(db_index=True, editable=False, max_length=32)),
                        ("job_suuid", models.CharField(db_index=True, editable=False, max_length=32)),
                        ("run_suuid", models.CharField(db_index=True, editable=False, max_length=32)),
                        (
                            "variable",
                            models.JSONField(default=None, editable=False, help_text="JSON field to store a variable"),
                        ),
                        ("is_masked", models.BooleanField(default=False)),
                        (
                            "label",
                            models.JSONField(
                                default=None,
                                editable=False,
                                help_text="JSON field as list with multiple objects which are labels",
                            ),
                        ),
                        ("created", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                    ],
                    options={
                        "verbose_name": "Run Variables Row",
                        "verbose_name_plural": "Run Variables Rows",
                        "db_table": "run_variablerow",
                        "ordering": ["-created"],
                    },
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name="runvariablerow",
                    index=django.contrib.postgres.indexes.GinIndex(
                        fields=["variable"], name="runvariable_variable_json_idx", opclasses=["jsonb_path_ops"]
                    ),
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name="runvariablerow",
                    index=django.contrib.postgres.indexes.GinIndex(
                        fields=["label"], name="runvariable_label_json_idx", opclasses=["jsonb_path_ops"]
                    ),
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="runvariable",
                    name="jobrun",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="runvariables", to="run.run"
                    ),
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name="runmetricrow",
                    index=django.contrib.postgres.indexes.GinIndex(
                        fields=["metric"], name="runmetric_metric_json_idx", opclasses=["jsonb_path_ops"]
                    ),
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name="runmetricrow",
                    index=django.contrib.postgres.indexes.GinIndex(
                        fields=["label"], name="runmetric_label_json_idx", opclasses=["jsonb_path_ops"]
                    ),
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="runmetric",
                    name="jobrun",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="metrics", to="run.run"
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
