# Generated by Django 3.2.15 on 2022-09-27 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0008_move_runmetrics_and_runvariables'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChunkedResultPart',
            new_name='ChunkedRunResultPart',
        ),
        migrations.RenameModel(
            old_name='Log',
            new_name='RunLog',
        ),
        migrations.RenameModel(
            old_name='Result',
            new_name='RunResult',
        ),
        migrations.AlterModelOptions(
            name='chunkedrunresultpart',
            options={'ordering': ['-created'], 'verbose_name': 'Run Result Chunk', 'verbose_name_plural': 'Run Result Chunks'},
        ),
        migrations.AlterModelOptions(
            name='runmetricrow',
            options={'ordering': ['-created'], 'verbose_name': 'Run Metric Row', 'verbose_name_plural': 'Run Metrics Rows'},
        ),
        migrations.AlterModelOptions(
            name='runresult',
            options={'ordering': ['-created'], 'verbose_name': 'Run Result', 'verbose_name_plural': 'Run Results'},
        ),
        migrations.AlterModelOptions(
            name='runvariablerow',
            options={'ordering': ['-created'], 'verbose_name': 'Run Variable Row', 'verbose_name_plural': 'Run Variables Rows'},
        ),
        migrations.AlterModelTable(
            name='runlog',
            table='run_log',
        ),
        migrations.AlterModelTable(
            name='runresult',
            table='run_result',
        ),
    ]
