# Generated by Django 3.2.15 on 2022-09-27 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "__first__"),
        ("run", "0010_auto_20220927_1921"),
    ]

    operations = [
        migrations.AlterField(
            model_name="run",
            name="run_image",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="job.runimage"),
        ),
    ]
