# Generated by Django 3.2.15 on 2022-09-27 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_auto_20220927_2033'),
        ('run', '0010_auto_20220927_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='run_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.runimage'),
        ),
    ]
