# Generated by Django 3.2.16 on 2022-10-15 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0011_alter_run_run_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runartifact',
            old_name='jobrun',
            new_name='run',
        ),
        migrations.RenameField(
            model_name='runlog',
            old_name='jobrun',
            new_name='run',
        ),
        migrations.RenameField(
            model_name='runmetric',
            old_name='jobrun',
            new_name='run',
        ),
        migrations.RenameField(
            model_name='runvariable',
            old_name='jobrun',
            new_name='run',
        ),
    ]
