# Generated by Django 3.2.16 on 2022-11-07 08:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0013_rename_short_uuid_to_suuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunkedrunartifactpart',
            name='suuid',
            field=models.CharField(editable=False, max_length=32, unique=True, verbose_name='SUUID'),
        ),
        migrations.AlterField(
            model_name='chunkedrunartifactpart',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='chunkedrunresultpart',
            name='suuid',
            field=models.CharField(editable=False, max_length=32, unique=True, verbose_name='SUUID'),
        ),
        migrations.AlterField(
            model_name='chunkedrunresultpart',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='run',
            name='suuid',
            field=models.CharField(editable=False, max_length=32, unique=True, verbose_name='SUUID'),
        ),
        migrations.AlterField(
            model_name='run',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='runartifact',
            name='suuid',
            field=models.CharField(editable=False, max_length=32, unique=True, verbose_name='SUUID'),
        ),
        migrations.AlterField(
            model_name='runartifact',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='runlog',
            name='suuid',
            field=models.CharField(editable=False, max_length=32, unique=True, verbose_name='SUUID'),
        ),
        migrations.AlterField(
            model_name='runlog',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='runmetric',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='runmetricrow',
            name='suuid',
            field=models.CharField(editable=False, max_length=32, unique=True, verbose_name='SUUID'),
        ),
        migrations.AlterField(
            model_name='runmetricrow',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='runresult',
            name='suuid',
            field=models.CharField(editable=False, max_length=32, unique=True, verbose_name='SUUID'),
        ),
        migrations.AlterField(
            model_name='runresult',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='runvariable',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='runvariablerow',
            name='suuid',
            field=models.CharField(editable=False, max_length=32, unique=True, verbose_name='SUUID'),
        ),
        migrations.AlterField(
            model_name='runvariablerow',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
    ]
