# Generated by Django 4.1.7 on 2023-03-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("run", "0022_move_field_to_core_iso_third_party_app"),
    ]

    operations = [
        migrations.AlterField(
            model_name="run",
            name="jobid",
            field=models.CharField(blank=True, default="", help_text="The job-id of the Celery run", max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="run",
            name="trigger",
            field=models.CharField(blank=True, default="API", max_length=20),
        ),
        migrations.AlterField(
            model_name="runresult",
            name="mime_type",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                help_text="Storing the mime-type of the output file",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="runresult",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
    ]
