# Generated by Django 4.1.8 on 2023-04-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("run", "0024_rename_jobid_run_celery_job_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="run",
            name="celery_task_id",
            field=models.CharField(blank=True, help_text="The task ID of the Celery run", max_length=120),
        ),
    ]
