tasks:
  - init: |
      python -m venv .venv
      source .venv/bin/activate
      pip install -r requirements/local.txt
    command: |
      source .venv/bin/activate
      pre-commit install --install-hooks
  - init: |
      cp .env.django.example .env.django
      cp .env.postgres.example .env.postgres
    command: |
      docker-compose up --detach --build

ports:
  - name: AskAnna Backend
    description: The AskAnna Backend application
    port: 8000
    visibility: public
  - name: AskAnna Flower
    description: Flower for monitoring Celery
    port: 5555
    visibility: private

vscode:
  extensions:
    - EditorConfig.EditorConfig
    - eamodio.gitlens
    - GitLab.gitlab-workflow
    - ms-python.python
    - batisteo.vscode-django
    - yzhang.markdown-all-in-one
    - TakumiI.markdowntable
    - ms-azuretools.vscode-docker
    - jeff-hykin.better-dockerfile-syntax
    - timonwong.shellcheck
    - ZainChen.json
