image:
    file: .gitpod.Dockerfile

additionalRepositories:
  - url: https://gitlab.askanna.io/askanna/askanna-frontend/
  - url: https://gitlab.askanna.io/askanna/askanna-cli/
  - url: https://gitlab.askanna.io/askanna/askanna-docs/

workspaceLocation: askanna-backend/.gitpod.askanna.code-workspace

tasks:
  - name: Docker Backend
    init: |
      cp .env.django.example .env.django
      cp .env.postgres.example .env.postgres
      cp .env.minio.example .env.minio
    command: |
      sed -i "s~ASKANNA_API_URL.*~ASKANNA_API_URL=$(gp url 8000)~g" .env.django
      sed -i "s~ASKANNA_UI_URL.*~ASKANNA_UI_URL=$(gp url 4173)~g" .env.django
      docker compose up --detach --build
      while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:8000/ht/)" != "200" ]]; do sleep 5; done
      docker compose exec -e DJANGO_SUPERUSER_PASSWORD=DevAskAnna django python manage.py createsuperuser --username admin@localhost.com --email admin@localhost.com --noinput
      docker compose logs --follow django
  - name: Vite Frontend Preview
    before: |
      cd ../askanna-frontend
    init: |
      cp .env.development .env.production.local
    command: |
      sed -i "s~VITE_APP_URL=.*~VITE_APP_URL=$(gp url 4173)~g" .env.production.local
      sed -i "s~VITE_APP_API_URL=.*~VITE_APP_API_URL=$(gp url 8000)~g" .env.production.local
      npm install
      npm run build
      npm run preview
  - name: MkDocs Documentation
    before: |
      cd ../askanna-docs
    init: |
      git lfs install && git lfs pull
      python -m venv .venv
    command: |
      source .venv/bin/activate
      pip install -r requirements-dev.txt
      mkdocs serve --dev-addr "127.0.0.1:8080"
  - name: Frontend
    command: |
      cd ../askanna-frontend
  - name: Documentation
    command: |
      cd ../askanna-docs
      source .venv/bin/activate
      pre-commit install --install-hooks
  - name: CLI & SDK
    before: |
      cd ../askanna-cli
    init: |
      python -m venv .venv
    command: |
      source .venv/bin/activate
      make install-dev
      pre-commit install --install-hooks
      while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:8000/ht/)" != "200" ]]; do echo "Backend is not ready yet..." && sleep 10; done && echo "Backend is ready!"
      while ! command -v askanna > /dev/null; do echo "CLI & SDK is not ready yet..." && sleep 10; done && echo "CLI & SDK is ready!" && askanna login --remote $(gp url 8000) --email admin@localhost.com --password DevAskAnna
  - name: Backend
    init: |
      python -m venv .venv
    command: |
      source .venv/bin/activate
      pip install -r requirements/local.txt
      pre-commit install --install-hooks
      while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:4173/ht/)" != "200" ]]; do echo "Frontend is not ready yet..." && sleep 10; done && echo "Frontend is ready!"
      while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:8000/ht/)" != "200" ]]; do echo "Backend is not ready yet..." && sleep 10; done && echo "Backend is ready!"

ports:
  - name: Backend Dev
    description: The AskAnna Backend application in development mode
    port: 8000
    visibility: public
  - name: Backend Flower
    description: Flower for monitoring Celery
    port: 5555
    visibility: private
  - name: Frontend Dev
    description: The AskAnna Frontend application in development mode
    port: 5173
    visibility: private
  - name: Frontend Preview
    description: The AskAnna Frontend application in review mode
    port: 4173
    visibility: private
  - name: Documentation
    description: The AskAnna documentation
    port: 8080
    visibility: private

vscode:
  extensions:
    - EditorConfig.EditorConfig
    - eamodio.gitlens
    - GitLab.gitlab-workflow
    - ms-python.python
    - charliermarsh.ruff
    - njpwerner.autodocstring
    - batisteo.vscode-django
    - DavidAnson.vscode-markdownlint
    - yzhang.markdown-all-in-one
    - TakumiI.markdowntable
    - ms-azuretools.vscode-docker
    - jeff-hykin.better-dockerfile-syntax
    - timonwong.shellcheck
    - ZainChen.json
    - octref.vetur
