variables:
  SENTRY_DSN: https://sentry.askanna.eu/askanna/askanna_backend
  DATABASE_URL: postgresql://anna:pass@postgres/askanna_backend
  REDIS_URL: redis://redis:6379/0
  CELERY_BROKER_URL: redis://redis:6379/0
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432
  POSTGRES_DB: askanna_backend
  POSTGRES_USER: anna
  POSTGRES_PASSWORD: pass

  DOCKER_REPO: ${CI_REGISTRY}/askanna/askanna-backend


stages:
  - build
  - test

test:
  services:
    - name: postgres:12
      alias: postgres
    - name: redis:5
      alias: redis
  image: $(DOCKER_REPO)/base:master
  stage: test
  before_script:
    - pip install -U pip
    - pip install -r requirements/local.txt
  script:
    - pytest

build_baseimage:
  image: docker:git
  stage: build
  tags:
    - normal
  variables:
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $(DOCKER_REPO)/base:$CI_COMMIT_REF_NAME -f compose/Dockerfile-base .
    - docker push $(DOCKER_REPO)/base:$CI_COMMIT_REF_NAME
  when: manual

build_production:
  image: docker:git
  stage: build
  tags:
    - normal
  variables:
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $(DOCKER_REPO):$CI_COMMIT_REF_NAME -f compose/production/django/Dockerfile .
    - docker push $(DOCKER_REPO):$CI_COMMIT_REF_NAME
  when: manual

build_production_image_aio:
  image: docker:git
  stage: build
  tags:
    - normal
  variables:
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $(DOCKER_REPO):$CI_COMMIT_REF_NAME -f compose/production/django/Dockerfile-aio .
    - docker push $(DOCKER_REPO):$CI_COMMIT_REF_NAME
  when: manual
