tasks:
  - name: Python
    before: |
      python -m venv .venv && source .venv/bin/activate
      pip install --upgrade pip
      pip install -r requirements/local.txt
      pre-commit install --install-hooks
    init: |
      mkdir .vscode && ln -n .gitpod-vscode-settings.json .vscode/settings.json
    command: |
      [[ -n $GPG_KEY ]] && [[ -n $GPG_SIGNING_KEY ]] \
        && echo 'pinentry-mode loopback' >> ~/.gnupg/gpg.conf \
        && gpg --verbose --batch --import <(echo $GPG_KEY|base64 -d) \
        && git config --global user.signingkey $GPG_SIGNING_KEY \
        && git config --global commit.gpgsign true \
        && echo '>> Commits will be signed with a GPG key'
  - name: Docker
    init: |
      cp .env.django.example .env.django
      cp .env.postgres.example .env.postgres
      docker compose build
    command: |
      source .venv/bin/activate
      docker compose up --detach --build
      docker compose logs --follow django

ports:
  - name: AskAnna Backend
    description: The AskAnna Backend application
    port: 8000
    visibility: public
  - name: AskAnna Flower
    description: Flower for monitoring Celery
    port: 5555
    visibility: private

vscode:
  extensions:
    - EditorConfig.EditorConfig
    - eamodio.gitlens
    - GitLab.gitlab-workflow
    - ms-python.python
    - batisteo.vscode-django
    - yzhang.markdown-all-in-one
    - TakumiI.markdowntable
    - ms-azuretools.vscode-docker
    - jeff-hykin.better-dockerfile-syntax
    - timonwong.shellcheck
    - ZainChen.json
