variables:
  SENTRY_DSN: https://sentry.askanna.eu/askanna/askanna_backend
  DATABASE_URL: postgresql://anna:pass@postgres/askanna_backend
  REDIS_URL: redis://redis:6379/0
  CELERY_BROKER_URL: redis://redis:6379/0
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432
  POSTGRES_DB: askanna_backend
  POSTGRES_USER: anna
  POSTGRES_PASSWORD: pass

  DOCKER_REPO: ${CI_REGISTRY}/askanna/askanna-backend


stages:
  - build_master
  - build
  - test
  - deploy
  - cleanup

test:
  services:
    - name: postgres:12
      alias: postgres
    - name: redis:5
      alias: redis
  image: ${DOCKER_REPO}/base:master
  stage: test
  before_script:
    - pip install -U pip
    - pip install -r requirements/local.txt
  script:
    - pytest

.build_baseimage: &build_baseimage
  image: docker:git
  stage: build_master
  tags:
    - normal
  variables:
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t ${DOCKER_REPO}/base:$CI_COMMIT_REF_NAME -f compose/Dockerfile-base .
    - docker push ${DOCKER_REPO}/base:$CI_COMMIT_REF_NAME

build_master_base:
  <<: *build_baseimage
  only:
    refs:
      - master
    changes:
      - compose/Dockerfile-base
      - requirements/base.txt
      - requirements/production.txt

build_branches_base:
  <<: *build_baseimage
  when: manual

build_production:
  image: docker:git
  stage: build
  tags:
    - normal
  variables:
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:19.03.5-dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t ${DOCKER_REPO}:$CI_COMMIT_REF_NAME -f compose/production/django/Dockerfile .
    - docker push ${DOCKER_REPO}:$CI_COMMIT_REF_NAME

stop_review:
  stage: cleanup
  image: curlimages/curl
  environment:
    name: $CI_COMMIT_REF_NAME
    action: stop
  when: manual
  allow_failure: true
  tags:
    - normal
  script:
    - curl -X POST -F token=${DEPLOY_TOKEN} -F ref=master -F variables[product]=backend -F variables[branch]=${CI_COMMIT_REF_NAME} -F variables[action]=undeploy ${TRIGGER_URL}
  except:
    - master

.deploy: &deploy
  image: curlimages/curl
  stage: deploy
  tags:
    - normal
  script:
    - curl -X POST -F token=${DEPLOY_TOKEN} -F ref=master -F variables[product]=backend -F variables[branch]=${CI_COMMIT_REF_NAME} -F variables[action]=deploy -F variables[slug]=${CI_ENVIRONMENT_SLUG} ${TRIGGER_URL}

deploy_branch:
  <<: *deploy
  environment:
    name: $CI_COMMIT_REF_NAME
    url: https://${CI_ENVIRONMENT_SLUG}-api.askanna.eu
    on_stop: stop_review
  except:
    refs:
      - master

deploy_master:
  <<: *deploy
  environment:
    name: master
    url: https://api.askanna.eu
  only:
    refs:
      - master
