variables:
  DATABASE_URL: postgresql://anna:pass@postgres/askanna_backend
  RUNINFO_DATABASE_URL: postgresql://anna:pass@postgres/runinfo
  REDIS_URL: redis://redis:6379/0
  CELERY_BROKER_URL: redis://redis:6379/0
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432
  POSTGRES_DB: askanna_backend
  POSTGRES_USER: anna
  POSTGRES_PASSWORD: pass

  DOCKER_REPO: $CI_REGISTRY_IMAGE

include:
  - template: Code-Quality.gitlab-ci.yml

stages:
  - build_baseimage
  - test
  - build
  - deploy
  - cleanup

test:
  stage: test
  image: ${DOCKER_REPO}/base:master
  services:
    - name: postgres:12
      alias: postgres
    - name: redis:5
      alias: redis
  tags:
    - kubernetes
  variables:
    DJANGO_SECRET_KEY: $CI_COMMIT_SHA
    DJANGO_ALLOWED_HOSTS: "*"
    DJANGO_EMAIL_BACKEND: "django.core.mail.backends.locmem.EmailBackend"
    DJANGO_SECURE_SSL_REDIRECT: "False"
  before_script:
    - pip install -U pip
    - pip install -r requirements/local.txt
  script:
    - pytest --cov=askanna_backend --cov-report=xml --junitxml=report.junit.xml
    - cat coverage.xml | sed -e "s.filename=\".filename=\"askanna_backend/.g" > report.coverage.xml
    - coverage html
    - coverage report
  coverage: '/TOTAL\s+\d+\s+\d+\s+\d+\s+\d+\s+([\d\.]+)\%/'
  artifacts:
    expire_in: 2 weeks
    name: "${CI_JOB_NAME}-${CI_COMMIT_REF_SLUG}"
    paths:
      - htmlcov/
    reports:
      cobertura: report.coverage.xml
      junit: report.junit.xml

code_quality:
  stage: test
  tags:
    - docker

.build_baseimage: &build_baseimage
  stage: build_baseimage
  tags:
    - kubernetes
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/compose/Dockerfile-base --destination ${DOCKER_REPO}/base:$CI_COMMIT_REF_NAME

build_master_base:
  <<: *build_baseimage
  only:
    refs:
      - master
    changes:
      - compose/Dockerfile-base
      - requirements/base.txt
      - requirements/production.txt

build_branches_base:
  <<: *build_baseimage
  when: manual

build_production:
  stage: build
  tags:
    - kubernetes
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/compose/production/django/Dockerfile --destination ${DOCKER_REPO}:$CI_COMMIT_REF_SLUG

stop_review:
  variables:
    GIT_STRATEGY: none
  stage: cleanup
  image: curlimages/curl
  environment:
    name: $CI_COMMIT_REF_NAME
    action: stop
  when: manual
  allow_failure: true
  tags:
    - kubernetes
  script:
    - curl -X POST -F token=${DEPLOY_TOKEN} -F ref=master -F variables[product]=backend -F variables[branch]=${CI_COMMIT_REF_SLUG} -F variables[action]=undeploy -F variables[slug]=${CI_ENVIRONMENT_SLUG} ${TRIGGER_URL}
  except:
    - master
    - beta

.deploy: &deploy
  variables:
    GIT_STRATEGY: none
  image: curlimages/curl
  stage: deploy
  tags:
    - kubernetes
  script:
    - curl -X POST -F token=${DEPLOY_TOKEN} -F ref=master -F variables[product]=backend -F variables[branch]=${CI_COMMIT_REF_SLUG} -F variables[action]=deploy -F variables[slug]=${CI_ENVIRONMENT_SLUG} ${TRIGGER_URL}

deploy_branch:
  <<: *deploy
  environment:
    name: $CI_COMMIT_REF_NAME
    url: https://${CI_ENVIRONMENT_SLUG}-api.askanna.eu/v1/docs/swagger
    on_stop: stop_review
  except:
    refs:
      - master

deploy_master:
  <<: *deploy
  environment:
    name: master
    url: https://api.askanna.eu/v1/docs/swagger
  only:
    refs:
      - master
