variables:
  SENTRY_DSN: https://sentry.askanna.eu/askanna/askanna_backend
  DATABASE_URL: postgresql://anna:pass@postgres/askanna_backend

stages:
  - test

test:
  services:
    - name: postgres:12
      alias: postgres
  image: python:3-slim
  stage: test
  before_script:
    - apt install postgresql-client
    - pip install -U pip
    - pip install -r requirements/local.txt
  script:
    - pytest