exclude: "docs|node_modules|migrations|.git|.tox"
default_stages: [commit]
fail_fast: true
default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: end-of-file-fixer
      - id: trailing-whitespace
        files: (^|/)a/.+\.(py|html|sh|css|js)$

  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args:
          [
            "--config=setup.cfg",
            "--ignore=W391,W503,E203",
            "--max-line-length=119",
          ]
