version: '3'

x-templates:
  restart-policy:
    &restart-policy
    restart: on-failure

  base-build-django:
    &base-build-django
    context: .
    dockerfile: ./compose/local/django/Dockerfile

  base-django:
    &base-django
    build:
      <<: *base-build-django
    <<: *restart-policy
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file:
      - .env.django
      - .env.postgres

services:
  #                       #
  # Third party images    #
  #                       #
  postgres:
    image: postgres:12-alpine
    <<: *restart-policy
    volumes:
      - db_volume:/var/lib/postgresql/data
    env_file:
      - .env.postgres

  redis:
    image: redis:7
    <<: *restart-policy
    volumes:
      - redis_volume:/data

  #                       #
  # AskAnna images        #
  #                       #
  # For development, you don't need the AskAnna Backup Helper. If you want to use the backup helper, feel free to
  # uncomment the following lines.
  #
  # backup_helper:
  #   image: askanna/backup-helper
  #   <<: *restart-policy
  #   volumes:
  #     - backup_volume:/backups
  #     - storage_volume:/data
  #   env_file:
  #     - .env.django
  #     - .env.postgres

  #                       #
  # Project images        #
  #                       #
  django:
    <<: *base-django
    build:
      <<: *base-build-django
      target: django
    depends_on:
      - postgres
    command: /start
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"

  celeryworker:
    <<: *base-django
    depends_on:
      - redis
      - postgres
    command: /start-celeryworker

  celerybeat:
    <<: *base-django
    depends_on:
      - redis
      - postgres
    command: /start-celerybeat

  flower:
    <<: *base-django
    build:
      <<: *base-build-django
      target: flower
    depends_on:
      - postgres
    command: /start-flower
    ports:
      - "5555:5555"

volumes:
  storage_volume:
  db_volume:
  redis_volume:
  backup_volume:
