version: '3'

x-templates:
  restart-policy:
    &restart-policy
    restart: no

  base-build-django:
    &base-build-django
    context: .
    dockerfile: ./docker/local/django/Dockerfile

  base-django:
    &base-django
    build:
      <<: *base-build-django
    <<: *restart-policy
    depends_on:
      - postgres
      - redis
      - minio
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file:
      - .env.django
      - .env.postgres
      - .env.minio

services:
  #                       #
  # Third party images    #
  #                       #
  postgres:
    image: postgres:12-alpine
    <<: *restart-policy
    volumes:
      - db_volume:/var/lib/postgresql/data
    env_file:
      - .env.postgres

  redis:
    image: redis:7
    <<: *restart-policy
    volumes:
      - redis_volume:/data

  minio:
    image: minio/minio:RELEASE.2023-09-04T19-57-37Z
    <<: *restart-policy
    command: server /data --console-address ":9090"
    volumes:
      - minio_volume:/data
    ports:
      - "9000:9000"
      - "9090:9090"
    env_file:
      - .env.minio

  #                       #
  # AskAnna images        #
  #                       #
  # For development, you don't need the AskAnna Backup Helper. If you want to use the backup helper, feel free to
  # uncomment the following lines.
  #
  # backup_helper:
  #   image: askanna/backup-helper
  #   <<: *restart-policy
  #   volumes:
  #     - backup_volume:/backups
  #     - storage_volume:/data
  #   env_file:
  #     - .env.django
  #     - .env.postgres

  #                       #
  # Project images        #
  #                       #
  django:
    <<: *base-django
    build:
      <<: *base-build-django
      target: django
    command: /start
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"

  celeryworker:
    <<: *base-django
    command: /start-celeryworker

  celerybeat:
    <<: *base-django
    command: /start-celerybeat

  flower:
    <<: *base-django
    build:
      <<: *base-build-django
      target: flower
    command: /start-flower
    ports:
      - "5555:5555"

volumes:
  storage_volume:
  db_volume:
  redis_volume:
  backup_volume:
  minio_volume:
