version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: askanna_backend_local_django
    restart: on-failure
    depends_on:
      - postgres
      # - rabbitmq_stats
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.rabbitmq
      - ./.envs/.local/.postgres
    ports:
      - "8006:8000"
    command: /start
    environment:
      VIRTUAL_HOST: api.askanna.localhost
      VIRTUAL_PORT: 5000

#  rabbitmq_stats:
#    image: bitnami/rabbitmq:3.8
#    env_file:
#      - ./.envs/.local/.rabbitmq
#    environment:
#      - RABBITMQ_NODE_TYPE=stats
#      - RABBITMQ_NODE_NAME=rabbit@rabbitmq_stats
#    volumes:
#      - rabbitmqstats_data:/bitnami

#  rabbitmq_queue_disc1:
#    image: bitnami/rabbitmq:3.8
#    depends_on:
#      - rabbitmq_stats
#    env_file:
#      - ./.envs/.local/.rabbitmq
#    environment:
#      - RABBITMQ_CLUSTER_NODE_NAME=rabbit@rabbitmq_stats
#      - RABBITMQ_NODE_TYPE=queue-disc
#      - RABBITMQ_NODE_NAME=rabbit@rabbitmq_queue_disc1
#    volumes:
#      - rabbitmqdisc1_data:/bitnami

#  rabbitmq_queue_ram1:
#    image: bitnami/rabbitmq:3.8
#    depends_on:
#      - rabbitmq_stats
#    env_file:
#      - ./.envs/.local/.rabbitmq
#    environment:
#      - RABBITMQ_CLUSTER_NODE_NAME=rabbit@rabbitmq_stats
#      - RABBITMQ_NODE_TYPE=queue-ram
#      - RABBITMQ_NODE_NAME=rabbit@rabbitmq_queue_ram1
#    volumes:
#      - rabbitmqram1_data:/bitnami

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: askanna_backend_production_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  redis:
    image: redis:5.0

  celeryworker:
    <<: *django
    image: askanna_backend_local_celeryworker
    depends_on:
      - redis
      - postgres
      #- rabbitmq_stats
    ports: []
    command: /start-celeryworker
    environment:
      NOTSET: 1

  celerybeat:
    <<: *django
    image: askanna_backend_local_celerybeat
    depends_on:
      - redis
      - postgres
      #- rabbitmq_stats
    ports: []
    command: /start-celerybeat
    environment:
      NOTSET: 1

  flower:
    <<: *django
    image: askanna_backend_local_flower
    ports:
      - "5556:5555"
    command: /start-flower
    environment:
      NOTSET: 1

volumes:
  static_volume:
  media_volume:
  local_postgres_data:
  local_postgres_data_backups:
  rabbitmqstats_data:
  rabbitmqdisc1_data:
  rabbitmqram1_data:
