[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings.test"
python_files = ["tests.py", "test_*.py", "*_tests.py"]
addopts="--capture=tee-sys"
norecursedirs = [".*", ".env", "storage_root"]
required_plugins = ["pytest-django", "Faker"]

[tool.black]
line-length = 119

[tool.isort]
profile = "black"
known_third_party = ["docker"]
known_local_folder = [
    "apps",
    "tests",
    "account",
    "core",
    "job",
    "package",
    "project",
    "run",
    "storage",
    "variable",
    "workspace"
]

[tool.bandit]
skips = ["B101"]

[tool.ruff]
target-version = "py311"
line-length = 119
select = [
    "F",   # pyflakes
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "UP",  # pyupgrade
    "DJ",  # flake8-django
    "N",   # pep8-naming
    "B",   # flake8-bugbear
    "C40", # flake8-comprehensions
    "ISC", # flake8-implicit-str-concat
    "T20", # flake8-print
    "RET", # flake8-return
    "PTH", # flake8-use-pathlib
]
exclude = [
    "tests/resources/*",
]

[tool.coverage.run]
branch = true
source = [
    "apps/*",
]
omit = [
    "admin.py",
    "*/migrations/*",
    "*/tests/*",
    "*.html",
    "*.txt",
    "*.sh",
]
plugins = [
    "django_coverage_plugin",
]

[tool.coverage.report]
precision = 2
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "def __str__",
    "raise AssertionError",
    "raise NotImplementedError",
    "if __name__ == .__main__.:",
]
