# Generated by Django 2.2.24 on 2021-11-28 23:01

from django.db import migrations, models
import django_cryptography.fields
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    replaces = [
        ("core", "0001_initial"),
        ("core", "0002_auto_20210707_1449"),
        ("core", "0003_setting_value"),
        ("core", "0004_remove_setting_old_value"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("deleted", models.DateTimeField(blank=True, null=True)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("short_uuid", models.CharField(blank=True, max_length=32, unique=True)),
                ("name", models.CharField(blank=True, max_length=32, unique=True)),
                ("value", django_cryptography.fields.encrypt(models.TextField(blank=True, default=None, null=True))),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
