# Generated by Django 4.1.8 on 2023-04-14 15:31

import uuid

import django_cryptography.fields
from django.db import migrations, models

import core.fields


class Migration(migrations.Migration):
    replaces = [
        ("core", "0001_initial_squashed_20220901"),
        ("core", "0002_rename_short_uuid_to_suuid"),
        ("core", "0003_uuid_and_suuid_field_config"),
        ("core", "0004_add_at_suffix_to_datetime_fields"),
        ("core", "0005_move_field_to_core_iso_third_party_app"),
        ("core", "0006_change_meta_options"),
    ]

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="UUID"
                    ),
                ),
                ("suuid", models.CharField(editable=False, max_length=32, unique=True, verbose_name="SUUID")),
                ("created_at", core.fields.CreationDateTimeField(auto_now_add=True)),
                ("modified_at", core.fields.ModificationDateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=32, unique=True)),
                ("value", django_cryptography.fields.encrypt(models.TextField(blank=True, default=None, null=True))),
            ],
            options={
                "ordering": ["-modified_at"],
                "get_latest_by": "modified_at",
                "abstract": False,
            },
        ),
    ]
