# Generated by Django 2.2.24 on 2021-07-07 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='value',
            new_name='old_value',
        ),
    ]
