# Generated by Django 3.2.16 on 2022-11-03 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial_squashed_20220901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='short_uuid',
            new_name='suuid',
        ),
    ]
