# Generated by Django 2.2.24 on 2021-07-07 14:50

from django.db import migrations, models
import django_cryptography.fields


def forwards_encrypted_char(apps, schema_editor):
    Setting = apps.get_model("core", "Setting")

    for row in Setting.objects.all():
        row.value = row.old_value
        row.save(update_fields=["value"])


def reverse_encrypted_char(apps, schema_editor):
    Setting = apps.get_model("core", "Setting")

    for row in Setting.objects.all():
        row.old_value = row.value
        row.save(update_fields=["old_value"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20210707_1449"),
    ]

    operations = [
        migrations.AddField(
            model_name="setting",
            name="value",
            field=django_cryptography.fields.encrypt(
                models.TextField(blank=True, default=None, null=True)
            ),
        ),
        migrations.RunPython(forwards_encrypted_char, reverse_encrypted_char),
    ]
