# Generated by Django 2.2.24 on 2021-07-07 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_setting_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='old_value',
        ),
    ]
