# Generated by Django 3.2.17 on 2023-02-22 14:05

from django.db import migrations
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_uuid_and_suuid_field_config"),
    ]

    operations = [
        migrations.RenameField(
            model_name="setting",
            old_name="deleted",
            new_name="deleted_at",
        ),
        migrations.RenameField(
            model_name="setting",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="setting",
            old_name="modified",
            new_name="modified_at",
        ),
        migrations.AlterField(
            model_name="setting",
            name="created_at",
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="setting",
            name="modified_at",
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True),
        ),
    ]
