# Generated by Django 2.2.8 on 2020-02-06 15:01

import core.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowDef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('project', models.CharField(blank=True, max_length=30, null=True)),
                ('flowtype', models.CharField(choices=[('CHAIN', 'CHAIN'), ('GROUP', 'GROUP')], default='CHAIN', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('visible', models.BooleanField(default=True)),
                ('edgelist', models.TextField(blank=True, null=True)),
                ('graph', core.fields.JSONField(blank=True, null=True)),
                ('owner', models.CharField(blank=True, max_length=100, null=True)),
                ('version', models.CharField(blank=True, max_length=200, null=True)),
                ('nodes', models.ManyToManyField(blank=True, to='job.JobDef')),
            ],
            options={
                'verbose_name': 'Flow Definition',
                'verbose_name_plural': 'Flow Definitions',
            },
        ),
        migrations.CreateModel(
            name='FlowRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status', models.CharField(choices=[('SUBMITTED', 'SUBMITTED'), ('COMPLETED', 'COMPLETED'), ('PENDING', 'PENDING'), ('PAUSED', 'PAUSED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('FAILED', 'FAILED'), ('SUCCESS', 'SUCCESS')], max_length=20)),
                ('jobids', core.fields.JSONField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.CharField(blank=True, max_length=100, null=True)),
                ('flowdef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flowruns', to='flow.FlowDef', to_field='uuid')),
            ],
            options={
                'verbose_name': 'Flow Run',
                'verbose_name_plural': 'Flow Runs',
            },
        ),
    ]
