# Generated by Django 2.2.8 on 2020-01-24 15:54

import core.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowDef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=50)),
                ('project', models.CharField(blank=True, max_length=30, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('visible', models.BooleanField(default=True)),
                ('edgelist', models.TextField(blank=True, null=True)),
                ('graph', core.fields.JSONField(blank=True, null=True)),
                ('owner', models.CharField(blank=True, max_length=100, null=True)),
                ('version', models.CharField(blank=True, max_length=200, null=True)),
                ('nodes', models.ManyToManyField(blank=True, null=True, to='job.JobDef')),
            ],
            options={
                'verbose_name': 'Flow Definition',
                'verbose_name_plural': 'Flow Definitions',
            },
        ),
    ]
