# Generated by Django 2.2.8 on 2020-01-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowdef',
            name='nodes',
            field=models.ManyToManyField(blank=True, to='job.JobDef'),
        ),
    ]
