# Generated by Django 2.2.8 on 2020-01-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0002_auto_20200128_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowdef',
            name='flowtype',
            field=models.CharField(choices=[('CHAIN', 'CHAIN'), ('GROUP', 'GROUP')], default='CHAIN', max_length=50),
        ),
    ]
