#!/bin/sh

set -o errexit
set -o nounset

rm -f './celerybeat.pid'

# celery -A config.celery_app beat -l INFO
watchmedo auto-restart --directory=./apps/ --pattern=*.py --recursive -- celery -A config.celery_app beat -l INFO
