# Generated by Django 4.1.8 on 2023-04-14 14:50

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.fields


class Migration(migrations.Migration):
    replaces = [
        ("job", "0001_initial_squashed_20220901"),
        ("job", "0002_auto_20220913_1349"),
        ("job", "0003_auto_20220920_1459"),
        ("job", "0004_move_run_result"),
        ("job", "0005_move_run_artifact"),
        ("job", "0006_move_projectvariable"),
        ("job", "0007_move_runmetrics_and_runvariables"),
        ("job", "0008_auto_20220927_2033"),
        ("job", "0009_rename_short_uuid_to_suuid"),
        ("job", "0010_uuid_and_suuid_field_config"),
        ("job", "0011_remove_translation"),
        ("job", "0012_description_do_not_allow_null_default_empty_string"),
        ("job", "0013_alter_jobdef_name"),
        ("job", "0014_add_unique_together_to_run_image"),
        ("job", "0015_add_db_index"),
        ("job", "0016_add_at_suffix_to_datetime_fields"),
        ("job", "0017_move_field_to_core_iso_third_party_app"),
        ("job", "0018_change_meta_options"),
        ("job", "0019_more_strict_in_allowing_null"),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account", "__first__"),
        ("project", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobDef",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="UUID"
                    ),
                ),
                ("suuid", models.CharField(editable=False, max_length=32, unique=True, verbose_name="SUUID")),
                ("created_at", core.fields.CreationDateTimeField(auto_now_add=True)),
                ("modified_at", core.fields.ModificationDateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField(blank=True, default="")),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("environment_image", models.CharField(blank=True, editable=False, max_length=2048)),
                ("timezone", models.CharField(default="UTC", max_length=256)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="project.project"
                    ),
                ),
            ],
            options={
                "verbose_name": "Job definition",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScheduledJob",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="UUID"
                    ),
                ),
                ("suuid", models.CharField(editable=False, max_length=32, unique=True, verbose_name="SUUID")),
                ("created_at", core.fields.CreationDateTimeField(auto_now_add=True)),
                ("modified_at", core.fields.ModificationDateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("raw_definition", models.CharField(max_length=128)),
                ("cron_definition", models.CharField(max_length=128)),
                ("cron_timezone", models.CharField(max_length=64)),
                ("last_run_at", models.DateTimeField(help_text="The last run of this scheduled job", null=True)),
                (
                    "next_run_at",
                    models.DateTimeField(
                        help_text="We store the datetime with timzone in UTC of the next run to be queried on",
                        null=True,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="job.jobdef",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="account.membership"),
                ),
            ],
            options={
                "ordering": ["-modified_at"],
                "get_latest_by": "modified_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RunImage",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="UUID"
                    ),
                ),
                ("suuid", models.CharField(editable=False, max_length=32, unique=True, verbose_name="SUUID")),
                ("created_at", core.fields.CreationDateTimeField(auto_now_add=True)),
                ("modified_at", core.fields.ModificationDateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField(blank=True, default="")),
                ("name", models.CharField(db_index=True, editable=False, max_length=255)),
                ("tag", models.CharField(blank=True, default="", editable=False, max_length=128)),
                ("digest", models.CharField(editable=False, max_length=256)),
                ("cached_image", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("name", "tag", "digest")},
            },
        ),
        migrations.CreateModel(
            name="JobPayload",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="UUID"
                    ),
                ),
                ("suuid", models.CharField(editable=False, max_length=32, unique=True, verbose_name="SUUID")),
                ("created_at", core.fields.CreationDateTimeField(auto_now_add=True)),
                ("modified_at", core.fields.ModificationDateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("size", models.PositiveIntegerField(default=0, editable=False)),
                ("lines", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "jobdef",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="payload", to="job.jobdef"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="jobdef",
            index=models.Index(fields=["name", "created_at"], name="job_jobdef_name_1799bb_idx"),
        ),
    ]
