# Generated by Django 2.2.8 on 2020-03-31 21:39

import core.fields
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDef',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('short_uuid', models.CharField(blank=True, max_length=32)),
                ('name', models.CharField(max_length=50)),
                ('function', models.CharField(blank=True, help_text='Function to execute', max_length=100, null=True)),
                ('backend', models.CharField(choices=[('job.celerybackend.CeleryJob', 'Celery')], default='job.celerybackend.CeleryJob', max_length=100)),
                ('visible', models.BooleanField(default=True)),
                ('environment', models.CharField(choices=[('python2.7', 'python2.7'), ('python3.5', 'python3.5'), ('python3.6', 'python3.6'), ('python3.7', 'python3.7')], default='python3.5', max_length=20)),
                ('env_variables', models.TextField(blank=True, null=True)),
                ('owner', models.CharField(blank=True, max_length=100, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.Project')),
            ],
            options={
                'verbose_name': 'Job Definition',
                'verbose_name_plural': 'Job Definitions',
            },
        ),
        migrations.CreateModel(
            name='JobRun',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('short_uuid', models.CharField(blank=True, max_length=32)),
                ('payload', models.UUIDField(blank=True, editable=False, null=True)),
                ('jobid', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'SUBMITTED'), ('COMPLETED', 'COMPLETED'), ('PENDING', 'PENDING'), ('PAUSED', 'PAUSED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('FAILED', 'FAILED'), ('SUCCESS', 'SUCCESS')], max_length=20)),
                ('runtime', models.FloatField(default=0)),
                ('memory', models.FloatField(default=0)),
                ('owner', models.CharField(blank=True, max_length=100, null=True)),
                ('jobdef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.JobDef')),
            ],
            options={
                'verbose_name': 'Job Run',
                'verbose_name_plural': 'Job Runs',
            },
        ),
        migrations.CreateModel(
            name='JobPayload',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('short_uuid', models.CharField(blank=True, max_length=32)),
                ('payload', core.fields.JSONField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('owner', models.CharField(blank=True, max_length=100, null=True)),
                ('jobdef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payload', to='job.JobDef')),
            ],
            options={
                'verbose_name': 'Job Payload',
                'verbose_name_plural': 'Job Payloads',
            },
        ),
        migrations.CreateModel(
            name='JobOutput',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('short_uuid', models.CharField(blank=True, max_length=32)),
                ('jobdef', models.UUIDField(blank=True, editable=False, null=True)),
                ('exit_code', models.IntegerField(default=0)),
                ('return_payload', core.fields.JSONField(blank=True, null=True)),
                ('stdout', core.fields.JSONField(blank=True, null=True)),
                ('owner', models.CharField(blank=True, max_length=100, null=True)),
                ('jobrun', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='output', to='job.JobRun')),
            ],
            options={
                'verbose_name': 'Job Output',
                'verbose_name_plural': 'Job Outputs',
            },
        ),
    ]
