# Generated by Django 2.2.8 on 2020-02-06 15:01

import core.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobDef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('project', models.CharField(blank=True, max_length=30, null=True)),
                ('function', models.CharField(blank=True, help_text='Function to execute', max_length=100, null=True)),
                ('backend', models.CharField(choices=[('job.celerybackend.CeleryJob', 'Celery')], default='job.celerybackend.CeleryJob', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('visible', models.BooleanField(default=True)),
                ('environment', models.CharField(choices=[('python2.7', 'python2.7'), ('python3.5', 'python3.5'), ('python3.6', 'python3.6'), ('python3.7', 'python3.7')], default='python3.5', max_length=20)),
                ('env_variables', models.TextField(blank=True, null=True)),
                ('owner', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Job Definition',
                'verbose_name_plural': 'Job Definitions',
            },
        ),
        migrations.CreateModel(
            name='JobRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('payload', models.UUIDField(blank=True, editable=False, null=True)),
                ('jobid', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'SUBMITTED'), ('COMPLETED', 'COMPLETED'), ('PENDING', 'PENDING'), ('PAUSED', 'PAUSED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('FAILED', 'FAILED'), ('SUCCESS', 'SUCCESS')], max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('runtime', models.FloatField(default=0)),
                ('memory', models.FloatField(default=0)),
                ('owner', models.CharField(blank=True, max_length=100, null=True)),
                ('jobdef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.JobDef', to_field='uuid')),
            ],
            options={
                'verbose_name': 'Job Run',
                'verbose_name_plural': 'Job Runs',
            },
        ),
        migrations.CreateModel(
            name='JobPayload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('payload', core.fields.JSONField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('owner', models.CharField(blank=True, max_length=100, null=True)),
                ('jobdef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payload', to='job.JobDef', to_field='uuid')),
            ],
            options={
                'verbose_name': 'Job Payload',
                'verbose_name_plural': 'Job Payloads',
            },
        ),
        migrations.CreateModel(
            name='JobOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('jobdef', models.UUIDField(blank=True, editable=False, null=True)),
                ('exit_code', models.IntegerField(default=0)),
                ('return_payload', core.fields.JSONField(blank=True)),
                ('stdout', core.fields.JSONField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.CharField(blank=True, max_length=100, null=True)),
                ('jobrun', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='output', to='job.JobRun', to_field='uuid')),
            ],
            options={
                'verbose_name': 'Job Output',
                'verbose_name_plural': 'Job Outputs',
            },
        ),
    ]
