# Generated by Django 2.2.8 on 2020-02-06 14:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrun',
            name='output',
        ),
        migrations.AddField(
            model_name='jobdef',
            name='backend',
            field=models.CharField(choices=[('job.celerybackend.CeleryJob', 'Celery')], default='job.celerybackend.CeleryJob', max_length=100),
        ),
        migrations.AddField(
            model_name='jobdef',
            name='owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='joboutput',
            name='jobdef',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='joboutput',
            name='jobrun',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='output', to='job.JobRun', to_field='uuid'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joboutput',
            name='owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobpayload',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobpayload',
            name='jobdef',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='payload', to='job.JobDef', to_field='uuid'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpayload',
            name='owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobrun',
            name='jobid',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='jobrun',
            name='owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobdef',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='jobrun',
            name='jobdef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.JobDef', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='jobrun',
            name='memory',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='jobrun',
            name='payload',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='jobrun',
            name='runtime',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='jobrun',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'SUBMITTED'), ('COMPLETED', 'COMPLETED'), ('PENDING', 'PENDING'), ('PAUSED', 'PAUSED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('FAILED', 'FAILED'), ('SUCCESS', 'SUCCESS')], max_length=20),
        ),
        migrations.AlterField(
            model_name='jobrun',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
