# Generated by Django 2.2.8 on 2020-04-02 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import json
import os

def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    JobPayload = apps.get_model("job", "JobPayload")
    db_alias = schema_editor.connection.alias
    for jobpayload in JobPayload.objects.using(db_alias).all():
        jobdef = jobpayload.jobdef

        # store incoming data as payload (in file format)
        store_path = [
            settings.PROJECTS_ROOT,
            'payloads',
            jobdef.project.uuid.hex,
            jobpayload.short_uuid
        ]
        relative_storepath = [
            jobdef.project.uuid.hex,
            jobpayload.short_uuid,
            'payload.json'
        ]
        os.makedirs(os.path.join(*store_path), exist_ok=True)
        with open(os.path.join(*store_path, 'payload.json'), "w") as f:
            f.write(json.dumps(jobpayload.payload))
        jobpayload.storage_location = str(os.path.join(*relative_storepath))
        jobpayload.save()


def reverse_func(apps, schema_editor):
    JobPayload = apps.get_model("job", "JobPayload")
    db_alias = schema_editor.connection.alias
    for jobpayload in JobPayload.objects.using(db_alias).all():
        jobdef = jobpayload.jobdef

        # store incoming data as payload (in file format)
        store_path = [
            settings.PROJECTS_ROOT,
            'payloads',
            jobdef.project.uuid.hex,
            jobpayload.short_uuid
        ]
        with open(os.path.join(*store_path, 'payload.json'), "r") as f:
            jobpayload.payload = f.read()
            jobpayload.save()

        # remove file
        os.remove(os.path.join(*store_path, 'payload.json'))
        # remove directory of this payload
        os.rmdir(os.path.join(*store_path))



class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpayload',
            name='active',
        ),
        migrations.AddField(
            model_name='jobpayload',
            name='storage_location',
            field=models.CharField(default='', max_length=1000, null=True, blank=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobpayload',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
