# Generated by Django 2.2.8 on 2020-02-06 16:04

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboutput',
            name='return_payload',
            field=core.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joboutput',
            name='stdout',
            field=core.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobpayload',
            name='payload',
            field=core.fields.JSONField(blank=True, null=True),
        ),
    ]
