# Generated by Django 4.1.8 on 2023-04-19 12:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0001_initial_20230414"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobpayload",
            options={"get_latest_by": "created_at", "ordering": ["-created_at"]},
        ),
    ]
