# Generated by Django 3.2.15 on 2022-09-20 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0002_auto_20220913_1349"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChunkedJobOutputPart",
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="JobOutput",
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name="JobOutput",
                    table="run_log",
                ),
            ],
        ),
    ]
