# Generated by Django 2.2.8 on 2020-04-02 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20200402_0652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobdef',
            options={'ordering': ['-created'], 'verbose_name': 'Job Definition', 'verbose_name_plural': 'Job Definitions'},
        ),
        migrations.AlterModelOptions(
            name='jobpayload',
            options={'ordering': ['-created'], 'verbose_name': 'Job Payload', 'verbose_name_plural': 'Job Payloads'},
        ),
        migrations.AlterModelOptions(
            name='jobrun',
            options={'ordering': ['-created'], 'verbose_name': 'Job Run', 'verbose_name_plural': 'Job Runs'},
        ),
        migrations.RemoveField(
            model_name='jobpayload',
            name='payload',
        ),
    ]
