# Generated by Django 2.2.8 on 2020-03-31 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20200206_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdef',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.Project'),
        ),
    ]
