# Generated by Django 2.2.28 on 2022-06-15 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_metrics_and_variables_meta_for_old_runs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrun',
            name='duration',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='Duration of the run in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='jobrun',
            name='jobid',
            field=models.CharField(blank=True, help_text='The job-id of the Celery run', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='jobrun',
            name='payload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.JobPayload'),
        ),
    ]
