# Generated by Django 2.2.8 on 2020-04-07 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20200402_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpayload',
            name='storage_location',
        ),
    ]
