# Generated by Django 3.2.15 on 2022-09-23 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0004_move_run_result"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="ChunkedArtifactPart",
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name="ChunkedArtifactPart",
                    table="run_chunkedrunartifactpart",
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="JobArtifact",
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name="JobArtifact",
                    table="run_runartifact",
                ),
            ],
        ),
    ]
