# Generated by Django 2.2.8 on 2020-04-08 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_remove_jobpayload_storage_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdef',
            name='default_payload',
            field=models.ForeignKey(blank=True, help_text='Default payload to use when not provided', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobdefault', to='job.JobPayload'),
        ),
    ]
