# Generated by Django 2.2.8 on 2020-04-09 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_jobdef_default_payload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdef',
            name='default_payload',
            field=models.UUIDField(blank=True, help_text='Default payload to use when not provided', null=True),
        ),
    ]
