# Generated by Django 3.2.15 on 2022-09-27 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_move_runmetrics_and_runvariables'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobdef',
            options={'ordering': ['-created'], 'verbose_name': 'Job definition'},
        ),
        migrations.AlterModelOptions(
            name='jobpayload',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='runimage',
            options={'ordering': ['-created']},
        ),
    ]
