# Generated by Django 3.1.14 on 2022-08-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_add_artifact_counts_to_historical_runs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboutput',
            name='stdout',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='runmetrics',
            name='label_names',
            field=models.JSONField(blank=True, default=None, editable=False, help_text='Unique metric label names and data type for metric label', null=True),
        ),
        migrations.AlterField(
            model_name='runmetrics',
            name='metric_names',
            field=models.JSONField(blank=True, default=None, editable=False, help_text='Unique metric names and data type for metric', null=True),
        ),
        migrations.AlterField(
            model_name='runmetricsrow',
            name='label',
            field=models.JSONField(default=None, editable=False, help_text='JSON field as list with multiple objects which are labels'),
        ),
        migrations.AlterField(
            model_name='runmetricsrow',
            name='metric',
            field=models.JSONField(default=None, editable=False, help_text='JSON field as list with multiple objects which are metrics, but we limit to one'),
        ),
        migrations.AlterField(
            model_name='runvariablerow',
            name='label',
            field=models.JSONField(default=None, editable=False, help_text='JSON field as list with multiple objects which are labels'),
        ),
        migrations.AlterField(
            model_name='runvariablerow',
            name='variable',
            field=models.JSONField(default=None, editable=False, help_text='JSON field to store a variable'),
        ),
        migrations.AlterField(
            model_name='runvariables',
            name='label_names',
            field=models.JSONField(blank=True, default=None, editable=False, help_text='Unique variable label names and data type for variable label', null=True),
        ),
        migrations.AlterField(
            model_name='runvariables',
            name='variable_names',
            field=models.JSONField(blank=True, default=None, editable=False, help_text='Unique variable names and data type for variable', null=True),
        ),
    ]
