# Generated by Django 2.2.8 on 2020-05-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_auto_20200511_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpayload',
            name='lines',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='jobpayload',
            name='size',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
