# Generated by Django 3.2.16 on 2022-11-03 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_auto_20220927_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdef',
            old_name='short_uuid',
            new_name='suuid',
        ),
        migrations.RenameField(
            model_name='jobpayload',
            old_name='short_uuid',
            new_name='suuid',
        ),
        migrations.RenameField(
            model_name='runimage',
            old_name='short_uuid',
            new_name='suuid',
        ),
        migrations.RenameField(
            model_name='scheduledjob',
            old_name='short_uuid',
            new_name='suuid',
        ),
    ]
