# Generated by Django 2.2.8 on 2020-05-20 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_chunkedartifactpart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobartifact',
            name='jobdef',
        ),
    ]
