# Generated by Django 3.2.16 on 2022-12-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_description_do_not_allow_null_default_empty_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdef',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
