# Generated by Django 2.2.8 on 2020-05-28 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0005_auto_20200519_2059'),
        ('job', '0013_jobvariable'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrun',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='package.Package'),
        ),
    ]
