# Generated by Django 3.2.16 on 2022-12-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_alter_jobdef_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runimage',
            name='cached_image',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='runimage',
            name='digest',
            field=models.CharField(editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='runimage',
            name='name',
            field=models.CharField(db_index=True, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='runimage',
            name='tag',
            field=models.CharField(blank=True, default='', editable=False, max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='runimage',
            unique_together={('name', 'tag', 'digest')},
        ),
    ]
