# Generated by Django 2.2.8 on 2020-06-04 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_jobrun_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joboutput',
            name='return_payload',
        ),
    ]
