# Generated by Django 3.2.17 on 2023-02-22 14:05

from django.db import migrations, models
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0015_add_db_index"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="jobdef",
            name="job_jobdef_name_986320_idx",
        ),
        migrations.RenameField(
            model_name="jobdef",
            old_name="deleted",
            new_name="deleted_at",
        ),
        migrations.RenameField(
            model_name="jobpayload",
            old_name="deleted",
            new_name="deleted_at",
        ),
        migrations.RenameField(
            model_name="runimage",
            old_name="deleted",
            new_name="deleted_at",
        ),
        migrations.RenameField(
            model_name="scheduledjob",
            old_name="deleted",
            new_name="deleted_at",
        ),
        migrations.RenameField(
            model_name="scheduledjob",
            old_name="last_run",
            new_name="last_run_at",
        ),
        migrations.RenameField(
            model_name="scheduledjob",
            old_name="next_run",
            new_name="next_run_at",
        ),
        migrations.RenameField(
            model_name="jobdef",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="jobdef",
            old_name="modified",
            new_name="modified_at",
        ),
        migrations.AlterField(
            model_name="jobdef",
            name="created_at",
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="jobdef",
            name="modified_at",
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True),
        ),
        migrations.RenameField(
            model_name="jobpayload",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="jobpayload",
            old_name="modified",
            new_name="modified_at",
        ),
        migrations.AlterField(
            model_name="jobpayload",
            name="created_at",
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="jobpayload",
            name="modified_at",
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True),
        ),
        migrations.RenameField(
            model_name="runimage",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="runimage",
            old_name="modified",
            new_name="modified_at",
        ),
        migrations.AlterField(
            model_name="runimage",
            name="created_at",
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="runimage",
            name="modified_at",
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True),
        ),
        migrations.RenameField(
            model_name="scheduledjob",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="scheduledjob",
            old_name="modified",
            new_name="modified_at",
        ),
        migrations.AlterField(
            model_name="scheduledjob",
            name="created_at",
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="scheduledjob",
            name="modified_at",
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="jobdef",
            index=models.Index(fields=["name", "created_at"], name="job_jobdef_name_1799bb_idx"),
        ),
        migrations.AlterModelOptions(
            name="jobdef",
            options={"ordering": ["-created_at"], "verbose_name": "Job definition"},
        ),
        migrations.AlterModelOptions(
            name="jobpayload",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="runimage",
            options={"ordering": ["-created_at"]},
        ),
    ]
