# Generated by Django 2.2.8 on 2020-06-22 10:25

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_remove_joboutput_return_payload'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChunkedJobOutputPart',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('short_uuid', models.CharField(blank=True, max_length=32)),
                ('filename', models.CharField(max_length=500)),
                ('size', models.IntegerField(help_text='Size of this resultchunk')),
                ('file_no', models.IntegerField()),
                ('is_last', models.BooleanField(default=False)),
                ('joboutput', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.JobOutput')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
