# Generated by Django 2.2.8 on 2020-08-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0016_chunkedjoboutputpart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdef',
            name='environment',
            field=models.CharField(choices=[('python2.7', 'python2.7'), ('python3.5', 'python3.5'), ('python3.6', 'python3.6'), ('python3.7', 'python3.7')], default='python3.7', max_length=20),
        ),
    ]
