# Generated by Django 3.2.18 on 2023-02-28 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_move_field_to_core_iso_third_party_app'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledjob',
            options={'get_latest_by': 'modified_at', 'ordering': ['-modified_at']},
        ),
    ]
