# Generated by Django 2.2.8 on 2020-10-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_auto_20200803_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunkedartifactpart',
            name='short_uuid',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='chunkedjoboutputpart',
            name='short_uuid',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='jobartifact',
            name='short_uuid',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='jobdef',
            name='short_uuid',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='joboutput',
            name='short_uuid',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='jobpayload',
            name='short_uuid',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='jobrun',
            name='short_uuid',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='jobvariable',
            name='short_uuid',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
    ]
