# Generated by Django 2.2.8 on 2020-11-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0018_auto_20201028_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvariable',
            name='is_masked',
            field=models.BooleanField(default=False),
        ),
    ]
