# Generated by Django 2.2.8 on 2020-12-01 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0020_auto_20201119_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunkedartifactpart',
            name='artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.JobArtifact'),
        ),
        migrations.AlterField(
            model_name='chunkedjoboutputpart',
            name='joboutput',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.JobOutput'),
        ),
        migrations.AlterField(
            model_name='jobdef',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
        migrations.AlterField(
            model_name='joboutput',
            name='jobrun',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='output', to='job.JobRun'),
        ),
    ]
