# Generated by Django 2.2.8 on 2021-01-05 09:22

from django.db import migrations, models
import django.db.models.deletion
from users.models import MSP_WORKSPACE


def forwards_func(apps, schema_editor):
    """
    Fill the memberfield of a jobrun
    """
    JobRun = apps.get_model("job", "JobRun")

    for jobrun in JobRun.objects.all():

        if not jobrun.member:
            # first lookup which member this could be based on workspace
            in_workspace = jobrun.jobdef.project.workspace
            if not jobrun.owner:
                # this was a job run by the system or early stage not registered
                # skip for now
                continue

            member_query = jobrun.owner.memberships.filter(
                object_uuid=in_workspace.uuid,
                object_type=MSP_WORKSPACE,
                deleted__isnull=True,
            )
            if member_query.exists():
                # get the membership out of it
                membership = member_query.first()
                if membership:
                    jobrun.member = membership
            jobrun.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_auto_20201222_1508"),
        ("job", "0021_auto_20201201_1545"),
    ]

    operations = [
        migrations.RemoveField(model_name="jobrun", name="memory",),
        migrations.RemoveField(model_name="jobrun", name="runtime",),
        migrations.AddField(
            model_name="jobrun",
            name="member",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.Membership",
            ),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
