# Generated by Django 2.2.8 on 2021-01-20 10:40

import core.fields
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0022_auto_20210105_0922"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobrun",
            name="metric_labels",
            field=core.fields.ArrayField(
                base_field=models.CharField(max_length=4096),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.RemoveField(model_name="jobrun", name="description",),
        migrations.RemoveField(model_name="jobrun", name="title",),
        migrations.CreateModel(
            name="RunMetrics",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("deleted", models.DateTimeField(blank=True, null=True)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("metrics", core.fields.JSONField(blank=True, null=True)),
                ("count", models.PositiveIntegerField(default=0, editable=False)),
                ("size", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "jobrun",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="job.JobRun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Run Metrics",
                "verbose_name_plural": "Run Metrics",
                "ordering": ["-created"],
            },
        ),
    ]
