# Generated by Django 2.2.8 on 2021-01-20 10:40

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0022_auto_20210105_0922"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobrun",
            name="labels",
            field=core.fields.ArrayField(
                base_field=models.CharField(max_length=4096),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
