# Generated by Django 2.2.8 on 2021-02-16 09:04

import core.fields
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.utils.timezone
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0023_auto_20210211_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunMetricsRow',
            fields=[
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('short_uuid', models.CharField(blank=True, max_length=32, unique=True)),
                ('project_suuid', models.CharField(db_index=True, editable=False, max_length=32)),
                ('job_suuid', models.CharField(db_index=True, editable=False, max_length=32)),
                ('run_suuid', models.CharField(db_index=True, editable=False, max_length=32)),
                ('metric', core.fields.JSONField(help_text='JSON field as list with multiple objects which are metrics, but we limit to one for db scanning only')),
                ('label', core.fields.JSONField(help_text='JSON field as list with multiple objects which are labels')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='runmetricsrow',
            index=django.contrib.postgres.indexes.GinIndex(fields=['metric'], name='metric_json_index', opclasses=['jsonb_path_ops']),
        ),
        migrations.AddIndex(
            model_name='runmetricsrow',
            index=django.contrib.postgres.indexes.GinIndex(fields=['label'], name='label_json_index', opclasses=['jsonb_path_ops']),
        ),
    ]
