# Generated by Django 2.2.19 on 2021-03-26 14:54

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    """
    Update the mime-type field for old runs, force set to application/json
    """
    JobOutput = apps.get_model("job", "JobOutput")

    for output in JobOutput.objects.all():
        output.mime_type = "application/json"
        output.save(update_fields=["mime_type"])


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0025_auto_20210303_1621"),
    ]

    operations = [
        migrations.AddField(
            model_name="joboutput",
            name="lines",
            field=models.PositiveIntegerField(
                default=0, editable=False, help_text="Number of lines in the result"
            ),
        ),
        migrations.AddField(
            model_name="joboutput",
            name="mime_type",
            field=models.CharField(
                blank=True,
                help_text="Storing the mime-type of the output file",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="joboutput",
            name="size",
            field=models.PositiveIntegerField(
                default=0, editable=False, help_text="Size of the result stored"
            ),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
