# Generated by Django 2.2.19 on 2021-04-08 07:03

import core.fields
import core.models
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0026_auto_20210326_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunVariableRow',
            fields=[
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('short_uuid', models.CharField(blank=True, max_length=32, unique=True)),
                ('project_suuid', models.CharField(db_index=True, editable=False, max_length=32)),
                ('job_suuid', models.CharField(db_index=True, editable=False, max_length=32)),
                ('run_suuid', models.CharField(db_index=True, editable=False, max_length=32)),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_masked', models.BooleanField(default=False)),
                ('variable', core.fields.JSONField(help_text='JSON field to store a variable')),
                ('label', core.fields.JSONField(help_text='JSON field as list with multiple objects which are labels')),
            ],
            options={
                'verbose_name': 'Tracked Run Variable',
                'verbose_name_plural': 'Tracked Run Variables',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='jobrun',
            name='variable_keys',
            field=core.fields.ArrayField(base_field=models.CharField(max_length=8192), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='jobrun',
            name='variable_labels',
            field=core.fields.ArrayField(base_field=models.CharField(max_length=4096), blank=True, default=list, size=None),
        ),
        migrations.CreateModel(
            name='RunVariables',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField(default=0, editable=False)),
                ('size', models.PositiveIntegerField(default=0, editable=False)),
                ('jobrun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runvariables', to='job.JobRun')),
            ],
            options={
                'verbose_name': 'Run Variables',
                'verbose_name_plural': 'Run Variables',
                'ordering': ['-created'],
            },
            bases=(core.models.ArtifactModelMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='runvariablerow',
            index=django.contrib.postgres.indexes.GinIndex(fields=['label'], name='runvariable_var_json_idx', opclasses=['jsonb_path_ops']),
        ),
        migrations.AddIndex(
            model_name='runvariablerow',
            index=django.contrib.postgres.indexes.GinIndex(fields=['label'], name='runvariable_lbl_json_idx', opclasses=['jsonb_path_ops']),
        ),
    ]
