# Generated by Django 2.2.20 on 2021-04-11 20:25

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_auto_20201222_1508"),
        ("job", "0027_auto_20210408_0703"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="runvariablerow",
            options={
                "ordering": ["-created"],
                "verbose_name": "Run variable row",
                "verbose_name_plural": "Run variable rows",
            },
        ),
        migrations.AddField(
            model_name="jobrun",
            name="trigger",
            field=models.CharField(blank=True, max_length=20, null=True, default="API"),
        ),
        migrations.CreateModel(
            name="ScheduledJob",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("deleted", models.DateTimeField(blank=True, null=True)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "short_uuid",
                    models.CharField(blank=True, max_length=32, unique=True),
                ),
                ("raw_definition", models.CharField(max_length=128)),
                ("cron_definition", models.CharField(max_length=128)),
                ("cron_timezone", models.CharField(max_length=64)),
                (
                    "last_run",
                    models.DateTimeField(
                        help_text="The last run of this scheduled job", null=True
                    ),
                ),
                (
                    "next_run",
                    models.DateTimeField(
                        help_text="We store the datetime with timzone in UTC of the next run to be queried on",
                        null=True,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="job.JobDef",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.Membership",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
