# Generated by Django 2.2.20 on 2021-04-14 07:58

from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    JobRun = apps.get_model("job", "JobRun")

    for obj in JobRun.objects.all():
        obj.name = obj.title
        obj.save(update_fields=["name"])


def reverse_func(apps, schema_editor):
    JobRun = apps.get_model("job", "JobRun")

    for obj in JobRun.objects.all():
        obj.title = obj.name
        obj.save(update_fields=["title"])


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0028_auto_20210411_2025"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobrun",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="jobdef",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="scheduledjob",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="job.JobDef",
            ),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
