# Generated by Django 2.2.20 on 2021-04-14 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0029_auto_20210414_0758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdef',
            name='title',
        ),
        migrations.RemoveField(
            model_name='jobrun',
            name='title',
        ),
    ]
