# Generated by Django 2.2.24 on 2021-06-24 14:17
import os

from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion
import django_extensions.db.fields
import uuid

from core.utils import GoogleTokenGenerator


def forwards_func_setrunresult(apps, schema_editor):
    JobOutput = apps.get_model("job", "JobOutput")
    RunResult = apps.get_model("job", "RunResult")

    google_token = GoogleTokenGenerator()
    for obj in JobOutput.objects.all():
        filename = "result_{}.output".format(obj.uuid.hex)
        storage_location = os.path.join(
            obj.jobrun.jobdef.project.uuid.hex,
            obj.jobrun.jobdef.uuid.hex,
            obj.jobrun.uuid.hex,
        )
        stored_path = os.path.join(settings.ARTIFACTS_ROOT, storage_location, filename)

        if os.path.exists(stored_path):
            # we only create a RunResult object when there is actually
            # a file found on the filesystem
            new_obj = RunResult(
                job=obj.jobdef,
                run=obj.jobrun,
                mime_type=obj.mime_type,
                size=obj.size,
                lines=obj.lines,
                owner=obj.owner,
            )
            new_obj.short_uuid = google_token.create_token(uuid_in=new_obj.uuid)
            new_obj.save()
            new_obj.created = obj.created
            new_obj.modified = obj.modified
            new_obj.save(update_fields=["created", "modified"])


def reverse_func(apps, schema_editor):
    # there is no way back
    pass


def forwards_func_setrunimage(apps, schema_editor):
    JobRun = apps.get_model("job", "JobRun")
    RunImage = apps.get_model("job", "RunImage")

    old_run_image, _ = RunImage.objects.get_or_create(
        name="askanna/python:3.7", tag="3.7", digest="unknown"
    )

    for obj in JobRun.objects.all():
        obj.environment_name = "Python 3.7"
        obj.run_image = old_run_image
        obj.timezone = "UTC"
        obj.finished = obj.modified
        if not obj.started:
            # fix a migration where we added started but not set it.
            obj.started = obj.created

        obj.duration = (obj.finished - obj.started).seconds

        obj.save(
            update_fields=[
                "environment_name",
                "run_image",
                "timezone",
                "started",
                "finished",
                "duration",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0030_auto_20210414_0951"),
    ]

    operations = [
        migrations.CreateModel(
            name="RunImage",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("deleted", models.DateTimeField(blank=True, null=True)),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="name"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "short_uuid",
                    models.CharField(blank=True, max_length=32, unique=True),
                ),
                (
                    "tag",
                    models.CharField(
                        blank=True, editable=False, max_length=128, null=True
                    ),
                ),
                (
                    "digest",
                    models.CharField(
                        blank=True, editable=False, max_length=256, null=True
                    ),
                ),
                (
                    "cached_image",
                    models.CharField(
                        blank=True, editable=False, max_length=256, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Run image",
                "verbose_name_plural": "Run images",
                "ordering": ["-created"],
            },
        ),
        migrations.AddField(
            model_name="jobdef",
            name="environment_image",
            field=models.CharField(
                blank=True, editable=False, max_length=2048, null=True
            ),
        ),
        migrations.AddField(
            model_name="jobdef",
            name="timezone",
            field=models.CharField(default="UTC", max_length=256),
        ),
        migrations.AddField(
            model_name="jobrun",
            name="duration",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="jobrun",
            name="environment_name",
            field=models.CharField(default="", max_length=256),
        ),
        migrations.AddField(
            model_name="jobrun",
            name="finished",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="jobrun",
            name="started",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="jobrun",
            name="timezone",
            field=models.CharField(default="UTC", max_length=256),
        ),
        migrations.CreateModel(
            name="RunResult",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("deleted", models.DateTimeField(blank=True, null=True)),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="name"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "short_uuid",
                    models.CharField(blank=True, max_length=32, unique=True),
                ),
                ("job", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "mime_type",
                    models.CharField(
                        blank=True,
                        help_text="Storing the mime-type of the output file",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "size",
                    models.PositiveIntegerField(
                        default=0, editable=False, help_text="Size of the result stored"
                    ),
                ),
                (
                    "lines",
                    models.PositiveIntegerField(
                        default=0,
                        editable=False,
                        help_text="Number of lines in the result",
                    ),
                ),
                ("owner", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="job.JobRun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Run result",
                "verbose_name_plural": "Run results",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="ChunkedRunResultPart",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("deleted", models.DateTimeField(blank=True, null=True)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "short_uuid",
                    models.CharField(blank=True, max_length=32, unique=True),
                ),
                ("filename", models.CharField(max_length=500)),
                ("size", models.IntegerField(help_text="Size of this runresult")),
                ("file_no", models.IntegerField()),
                ("is_last", models.BooleanField(default=False)),
                (
                    "runresult",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="job.RunResult",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.AddField(
            model_name="jobrun",
            name="run_image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="job.RunImage",
            ),
        ),
        migrations.RunPython(forwards_func_setrunresult, reverse_func),
        migrations.RunPython(forwards_func_setrunimage, reverse_func),
    ]
