# Generated by Django 2.2.24 on 2021-07-07 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0031_custom_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobvariable',
            old_name='value',
            new_name='old_value',
        ),
    ]
