# Generated by Django 2.2.24 on 2021-07-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0032_custom_images_migrate_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrun',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'SUBMITTED'), ('PENDING', 'PENDING'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED')], max_length=20),
        ),
    ]
