# Generated by Django 2.2.24 on 2021-07-07 14:33

from django.db import migrations, models
import django_cryptography.fields


def forwards_encrypted_char(apps, schema_editor):
    JobVariable = apps.get_model("job", "JobVariable")

    for row in JobVariable.objects.all():
        row.value = row.old_value
        row.save(update_fields=["value"])


def reverse_encrypted_char(apps, schema_editor):
    JobVariable = apps.get_model("job", "JobVariable")

    for row in JobVariable.objects.all():
        row.old_value = row.value
        row.save(update_fields=["old_value"])


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0032_auto_20210707_1428"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobvariable",
            name="value",
            field=django_cryptography.fields.encrypt(
                models.TextField(blank=True, default=None, null=True)
            ),
        ),
        migrations.RunPython(forwards_encrypted_char, reverse_encrypted_char),
    ]
