# Generated by Django 2.2.24 on 2021-07-07 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0033_jobvariable_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobvariable',
            name='old_value',
        ),
    ]
