# Generated by Django 2.2.24 on 2021-09-09 12:47

from django.db import migrations


def forwards_func_setrunimage(apps, schema_editor):
    """
    in migration 0031 we made a mistake in the name, this migration is fixing that
    """
    RunImage = apps.get_model("job", "RunImage")

    old_run_image = RunImage.objects.get(
        name="askanna/python:3.7", tag="3.7", digest="unknown"
    )
    old_run_image.name = "askanna/python"
    old_run_image.save(update_fields=["name"])


def reverse_func(app, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0033_auto_20210726_1205"),
    ]

    operations = [
        migrations.RunPython(forwards_func_setrunimage, reverse_func),
    ]
