# Generated by Django 2.2.24 on 2021-09-16 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0034_remove_jobvariable_old_value'),
        ('job', '0034_fix_default_askanna_image'),
    ]

    operations = [
    ]
