# Generated by Django 3.2.16 on 2022-11-03 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_alter_workspace_visibility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workspace',
            old_name='short_uuid',
            new_name='suuid',
        ),
    ]
