# Generated by Django 2.2.20 on 2021-04-14 07:54

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    Workspace = apps.get_model("workspace", "Workspace")

    for obj in Workspace.objects.all():
        obj.name = obj.title
        obj.save(update_fields=["name"])


def reverse_func(apps, schema_editor):
    Workspace = apps.get_model("workspace", "Workspace")

    for obj in Workspace.objects.all():
        obj.title = obj.name
        obj.save(update_fields=["title"])


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0002_auto_20201028_2111"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="name"
            ),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
