# Generated by Django 2.2.24 on 2021-10-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0004_remove_workspace_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="visibility",
            field=models.CharField(
                default="PRIVATE", max_length=255, verbose_name="Visibility"
            ),
        ),
    ]
