# Generated by Django 3.2.16 on 2022-12-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0005_remove_translation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
