# Generated by Django 2.2.24 on 2021-10-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0005_workspace_visibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="visibility",
            field=models.CharField(
                db_index=True,
                default="PRIVATE",
                max_length=255,
                verbose_name="Visibility",
            ),
        ),
    ]
