# Generated by Django 3.2.16 on 2022-12-15 09:26

from django.db import migrations, models
from workspace.models import Workspace


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0005_remove_translation"),
    ]

    def forwards_func(apps, schema_editor):
        for workspace in Workspace.objects.filter(name__isnull=True):
            if not workspace.name:
                workspace.name = workspace.suuid
                workspace.save()

    def reverse_func(apps, schema_editor):
        pass

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
        migrations.AlterField(
            model_name="workspace",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
