# Generated by Django 3.2.16 on 2022-12-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0006_make_name_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='name',
            field=models.CharField(db_index=True, default='New workspace', max_length=255),
        ),
    ]
