# Generated by Django 3.2.16 on 2023-01-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0008_auto_20221222_0720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workspace',
            options={'ordering': ['name']},
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['name', 'created'], name='workspace_w_name_8599ec_idx'),
        ),
    ]
