# Generated by Django 3.2.17 on 2023-02-22 14:05

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0009_add_db_index"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="workspace",
            name="workspace_w_name_8599ec_idx",
        ),
        migrations.RenameField(
            model_name="workspace",
            old_name="deleted",
            new_name="deleted_at",
        ),
        migrations.RenameField(
            model_name="workspace",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="workspace",
            old_name="modified",
            new_name="modified_at",
        ),
        migrations.AlterField(
            model_name="workspace",
            name="created_at",
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="workspace",
            name="modified_at",
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="workspace",
            index=models.Index(fields=["name", "created_at"], name="workspace_w_name_044646_idx"),
        ),
    ]
