# -*- coding: utf-8 -*-
import datetime
import unittest

from core.utils import find_last_modified

filelist = [
    {
        "path": "README.md",
        "parent": "/",
        "name": "README.md",
        "is_dir": False,
        "size": 1821,
        "depth": 0,
        "last_modified": datetime.datetime(2020, 6, 25, 8, 42, 2),
        "type": "file",
    },
    {
        "path": "requirements.txt",
        "parent": "/",
        "name": "requirements.txt",
        "is_dir": False,
        "size": 49,
        "depth": 0,
        "last_modified": datetime.datetime(2020, 10, 7, 21, 16),
        "type": "file",
    },
    {
        "path": "askanna.yml",
        "parent": "/",
        "name": "askanna.yml",
        "is_dir": False,
        "size": 967,
        "depth": 0,
        "last_modified": datetime.datetime(2021, 2, 17, 10, 57, 28),
        "type": "file",
    },
    {
        "path": "docs/README.md",
        "parent": "docs",
        "name": "README.md",
        "is_dir": False,
        "size": 1318,
        "depth": 0,
        "last_modified": datetime.datetime(2020, 6, 25, 8, 47, 24),
        "type": "file",
    },
    {
        "path": "docs/.nojekyll",
        "parent": "docs",
        "name": ".nojekyll",
        "is_dir": False,
        "size": 0,
        "depth": 0,
        "last_modified": datetime.datetime(2020, 6, 25, 8, 46, 10),
        "type": "file",
    },
    {
        "path": "docs/sidebar.md",
        "parent": "docs",
        "name": "sidebar.md",
        "is_dir": False,
        "size": 20,
        "depth": 0,
        "last_modified": datetime.datetime(2020, 6, 25, 8, 42, 40),
        "type": "file",
    },
    {
        "path": "docs/index.html",
        "parent": "docs",
        "name": "index.html",
        "is_dir": False,
        "size": 2387,
        "depth": 0,
        "last_modified": datetime.datetime(2020, 6, 25, 8, 42, 40),
        "type": "file",
    },
    {
        "path": "docs/media/askanna.png",
        "parent": "docs/media",
        "name": "askanna.png",
        "is_dir": False,
        "size": 22130,
        "depth": 1,
        "last_modified": datetime.datetime(2020, 6, 25, 8, 43),
        "type": "file",
    },
    {
        "path": "docs/media/favicon.ico",
        "parent": "docs/media",
        "name": "favicon.ico",
        "is_dir": False,
        "size": 6782,
        "depth": 1,
        "last_modified": datetime.datetime(2020, 6, 25, 8, 43),
        "type": "file",
    },
    {
        "path": "result/evaluation.json",
        "parent": "result",
        "name": "evaluation.json",
        "is_dir": False,
        "size": 85,
        "depth": 0,
        "last_modified": datetime.datetime(2020, 8, 4, 11, 21, 28),
        "type": "file",
    },
    {
        "path": "result/prediction.json",
        "parent": "result",
        "name": "prediction.json",
        "is_dir": False,
        "size": 86,
        "depth": 0,
        "last_modified": datetime.datetime(2020, 6, 25, 14, 6, 44),
        "type": "file",
    },
    {
        "path": "result/.gitkeep",
        "parent": "result",
        "name": ".gitkeep",
        "is_dir": False,
        "size": 0,
        "depth": 0,
        "last_modified": datetime.datetime(2020, 6, 25, 14, 3, 56),
        "type": "file",
    },
    {
        "path": "data/interim/.gitkeep",
        "parent": "data/interim",
        "name": ".gitkeep",
        "is_dir": False,
        "size": 0,
        "depth": 1,
        "last_modified": datetime.datetime(2020, 4, 3, 10, 15, 26),
        "type": "file",
    },
    {
        "path": "data/input/.gitkeep",
        "parent": "data/input",
        "name": ".gitkeep",
        "is_dir": False,
        "size": 0,
        "depth": 1,
        "last_modified": datetime.datetime(2020, 4, 7, 9, 0, 36),
        "type": "file",
    },
    {
        "path": "data/processed/.gitkeep",
        "parent": "data/processed",
        "name": ".gitkeep",
        "is_dir": False,
        "size": 0,
        "depth": 1,
        "last_modified": datetime.datetime(2020, 4, 7, 9, 0, 46),
        "type": "file",
    },
    {
        "path": "src/__init__.py",
        "parent": "src",
        "name": "__init__.py",
        "is_dir": False,
        "size": 0,
        "depth": 0,
        "last_modified": datetime.datetime(2020, 6, 25, 8, 42, 2),
        "type": "file",
    },
    {
        "path": "src/models/train_model.py",
        "parent": "src/models",
        "name": "train_model.py",
        "is_dir": False,
        "size": 390,
        "depth": 1,
        "last_modified": datetime.datetime(2020, 11, 10, 16, 4, 30),
        "type": "file",
    },
    {
        "path": "src/models/evaluate_model.py",
        "parent": "src/models",
        "name": "evaluate_model.py",
        "is_dir": False,
        "size": 234,
        "depth": 1,
        "last_modified": datetime.datetime(2020, 8, 4, 11, 20, 28),
        "type": "file",
    },
    {
        "path": "src/models/serve_model.py",
        "parent": "src/models",
        "name": "serve_model.py",
        "is_dir": False,
        "size": 234,
        "depth": 1,
        "last_modified": datetime.datetime(2020, 6, 25, 8, 42, 2),
        "type": "file",
    },
    {
        "path": "src/models/test-multiple-models.py",
        "parent": "src/models",
        "name": "test-multiple-models.py",
        "is_dir": False,
        "size": 4159,
        "depth": 1,
        "last_modified": datetime.datetime(2021, 2, 2, 15, 4, 42),
        "type": "file",
    },
    {
        "path": "src/models/__init__.py",
        "parent": "src/models",
        "name": "__init__.py",
        "is_dir": False,
        "size": 0,
        "depth": 1,
        "last_modified": datetime.datetime(2020, 6, 25, 8, 42, 2),
        "type": "file",
    },
    {
        "path": "src/data/create_dataset.py",
        "parent": "src/data",
        "name": "create_dataset.py",
        "is_dir": False,
        "size": 899,
        "depth": 1,
        "last_modified": datetime.datetime(2020, 6, 25, 8, 42, 2),
        "type": "file",
    },
    {
        "path": "src/data/__init__.py",
        "parent": "src/data",
        "name": "__init__.py",
        "is_dir": False,
        "size": 0,
        "depth": 1,
        "last_modified": datetime.datetime(2020, 6, 25, 8, 42, 2),
        "type": "file",
    },
    {
        "path": "src/data/create_features.py",
        "parent": "src/data",
        "name": "create_features.py",
        "is_dir": False,
        "size": 234,
        "depth": 1,
        "last_modified": datetime.datetime(2020, 6, 25, 8, 42, 2),
        "type": "file",
    },
]


class TestArchive(unittest.TestCase):
    def test_last_modified(self):
        last_modified = datetime.datetime(2020, 6, 25, 8, 47, 24)
        found_last_modified = find_last_modified("docs", filelist)
        self.assertEqual(found_last_modified, last_modified)
