# Generated by Django 4.2.1 on 2023-05-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_setting_name_alter_setting_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="setting",
            name="name",
            field=models.CharField(
                choices=[
                    ("ASKANNA_UI_URL", "ASKANNA_UI_URL"),
                    ("DEFAULT_FROM_EMAIL", "DEFAULT_FROM_EMAIL"),
                    ("DOCKER_AUTO_REMOVE_TTL_HOURS", "DOCKER_AUTO_REMOVE_TTL_HOURS"),
                    ("DOCKER_PRINT_LOG", "DOCKER_PRINT_LOG"),
                    ("MINIO_SETTINGS", "MINIO_SETTINGS"),
                    ("OBJECT_REMOVAL_TTL_HOURS", "OBJECT_REMOVAL_TTL_HOURS"),
                    ("RUNNER_DEFAULT_DOCKER_IMAGE", "RUNNER_DEFAULT_DOCKER_IMAGE"),
                    ("RUNNER_DEFAULT_DOCKER_IMAGE_USERNAME", "RUNNER_DEFAULT_DOCKER_IMAGE_USERNAME"),
                    ("RUNNER_DEFAULT_DOCKER_IMAGE_PASSWORD", "RUNNER_DEFAULT_DOCKER_IMAGE_PASSWORD"),
                ],
                max_length=150,
                unique=True,
            ),
        ),
    ]
