# Generated by Django 4.2.4 on 2023-08-18 06:21

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account", "0002_alter_membership_job_title_delete_userprofile"),
        ("core", "0003_add_minio_settings"),
        ("package", "0002_alter_package_options"),
        ("run", "0002_update_run_created_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObjectReference",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="UUID"
                    ),
                ),
                (
                    "account_membership",
                    models.OneToOneField(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="account.membership"
                    ),
                ),
                (
                    "account_user",
                    models.OneToOneField(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "package_package",
                    models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to="package.package"),
                ),
                (
                    "run_run",
                    models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to="run.run"),
                ),
                (
                    "run_artifact",
                    models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to="run.runartifact"),
                ),
            ],
        ),
    ]
