# Generated by Django 4.2.4 on 2023-08-18 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account", "0002_alter_membership_job_title_delete_userprofile"),
        ("core", "0003_add_minio_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObjectReference",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="UUID"
                    ),
                ),
                (
                    "account_membership",
                    models.OneToOneField(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="account.membership"
                    ),
                ),
                (
                    "account_user",
                    models.OneToOneField(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
