# Generated by Django 4.2.4 on 2023-09-13 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("package", "0002_alter_package_options"),
        ("core", "0004_add_objectreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="objectreference",
            name="package_package",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="package.package"
            ),
        ),
    ]
