# Generated by Django 4.2.7 on 2023-11-28 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("run", "0002_update_run_created_by"),
        ("core", "0005_objectreference_add_package"),
    ]

    operations = [
        migrations.AddField(
            model_name="objectreference",
            name="run_artifact",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="run.runartifact"
            ),
        ),
    ]
