# Generated by Django 4.2.8 on 2023-12-06 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_alter_membership_object_type_alter_membership_role"),
        ("run", "0004_move_run_artifact_files_to_storage"),
        ("package", "0005_move_package_files_to_storage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0006_objectreference_add_run_artifact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objectreference",
            name="account_membership",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="account.membership"
            ),
        ),
        migrations.AlterField(
            model_name="objectreference",
            name="account_user",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="objectreference",
            name="package_package",
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to="package.package"),
        ),
        migrations.AlterField(
            model_name="objectreference",
            name="run_artifact",
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to="run.runartifact"),
        ),
    ]
