from django.db import models

from core.models import BaseModel


# TODO: remove RunLog model after release v0.29.0
class RunLog(BaseModel):
    """
    The log generated by a run
    """

    run = models.OneToOneField("run.Run", on_delete=models.CASCADE, related_name="output")
    exit_code = models.IntegerField(default=0)
    stdout = models.JSONField(blank=True, null=True)

    class Meta:
        db_table = "run_log"
        ordering = ["-created_at"]
