# Generated by Django 3.2.16 on 2022-12-22 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variable', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variable',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelTable(
            name='variable',
            table=None,
        ),
    ]
