# Generated by Django 3.2.17 on 2023-02-22 14:05

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("variable", "0002_auto_20221222_0720"),
    ]

    operations = [
        migrations.RenameField(
            model_name="variable",
            old_name="deleted",
            new_name="deleted_at",
        ),
        migrations.RenameField(
            model_name="variable",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="variable",
            old_name="modified",
            new_name="modified_at",
        ),
        migrations.AlterField(
            model_name="variable",
            name="created_at",
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="variable",
            name="modified_at",
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True),
        ),
        migrations.AlterModelOptions(
            name="variable",
            options={"ordering": ["-created_at"]},
        ),
    ]
