# Generated by Django 4.1.8 on 2023-04-14 15:18

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.fields


class Migration(migrations.Migration):
    replaces = [
        ("package", "0001_initial_squashed_20220901"),
        ("package", "0002_rename_short_uuid_to_suuid"),
        ("package", "0003_uuid_and_suuid_field_config"),
        ("package", "0004_alter_package_project"),
        ("package", "0005_remove_translation"),
        ("package", "0006_description_do_not_allow_null_default_empty_string"),
        ("package", "0007_add_at_suffix_to_datetime_fields"),
        ("package", "0008_move_field_to_core_iso_third_party_app"),
        ("package", "0009_more_strict_in_allowing_null"),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account", "__first__"),
        ("project", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="UUID"
                    ),
                ),
                ("suuid", models.CharField(editable=False, max_length=32, unique=True, verbose_name="SUUID")),
                ("created_at", core.fields.CreationDateTimeField(auto_now_add=True)),
                ("modified_at", core.fields.ModificationDateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("original_filename", models.CharField(default="", max_length=1000)),
                ("size", models.IntegerField(help_text="Size of this package in bytes")),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Date and time when upload of this package was finished",
                        null=True,
                        verbose_name="Finished upload at",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="account.membership"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packages",
                        to="project.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChunkedPackagePart",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("filename", models.CharField(max_length=500)),
                ("size", models.IntegerField(help_text="Size of this chunk of the package")),
                ("file_no", models.IntegerField()),
                ("is_last", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                (
                    "package",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="package.package"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
