# Generated by Django 4.1.8 on 2023-04-19 10:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("package", "0001_initial_20230414"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="package",
            options={"get_latest_by": "created_at", "ordering": ["-created_at"]},
        ),
    ]
