# Generated by Django 2.2.8 on 2020-05-19 13:50

import json
import os

from django.conf import settings
from django.db import migrations

def forwards_func(apps, schema_editor):
    Package = apps.get_model("package", "Package")

    for package in Package.objects.all():
        package.created = package.created_at
        package.modified = package.created_at
        package.deleted = package.deleted_at
        package.save(update_fields=['created', 'modified', 'deleted'])


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_auto_20200519_1348'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func, elidable=True),
    ]
