# Generated by Django 2.2.8 on 2020-07-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0006_short_uuid_missing'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='message',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
