# Generated by Django 3.2.17 on 2023-02-22 14:05

from django.db import migrations, models
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("package", "0006_description_do_not_allow_null_default_empty_string"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="package",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="package",
            old_name="deleted",
            new_name="deleted_at",
        ),
        migrations.RenameField(
            model_name="package",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="package",
            old_name="modified",
            new_name="modified_at",
        ),
        migrations.RenameField(
            model_name="package",
            old_name="finished",
            new_name="finished_at",
        ),
        migrations.AlterField(
            model_name="package",
            name="created_at",
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="package",
            name="modified_at",
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="package",
            name="finished_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Date and time when upload of this package was finished",
                null=True,
                verbose_name="Finished upload at",
            ),
        ),
    ]
