# Generated by Django 2.2.8 on 2020-12-01 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0008_auto_20201028_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunkedpackagepart',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='package.Package'),
        ),
        migrations.AlterField(
            model_name='package',
            name='project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', related_query_name='package', to='project.Project'),
        ),
    ]
