# Generated by Django 2.2.8 on 2020-12-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0009_auto_20201201_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='original_filename',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
