# Generated by Django 2.2.8 on 2021-01-05 11:12

from django.db import migrations, models
import django.db.models.deletion

from users.models import MSP_WORKSPACE


def forwards_func(apps, schema_editor):
    """
    Fill the memberfield of a package
    """
    Package = apps.get_model("package", "Package")

    for package in Package.objects.all():

        if not package.member:
            # first lookup which member this could be based on workspace
            in_workspace = package.project.workspace
            if not package.created_by:
                # this was a job run by the system or early stage not registered
                # skip for now
                continue

            member_query = package.created_by.memberships.filter(
                object_uuid=in_workspace.uuid,
                object_type=MSP_WORKSPACE,
                deleted__isnull=True,
            )
            if member_query.exists():
                # get the membership out of it
                membership = member_query.first()
                if membership:
                    package.member = membership
            package.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_auto_20201222_1508"),
        ("package", "0012_remove_package_filename"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="member",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.Membership",
            ),
        ),
        migrations.RunPython(forwards_func, reverse_func, elidable=True),
    ]
