# Generated by Django 2.2.20 on 2021-04-14 07:54

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    Package = apps.get_model("package", "Package")

    for obj in Package.objects.all():
        obj.name = obj.title
        obj.save(update_fields=["name"])


def reverse_func(apps, schema_editor):
    Package = apps.get_model("package", "Package")

    for obj in Package.objects.all():
        obj.title = obj.name
        obj.save(update_fields=["title"])


class Migration(migrations.Migration):

    dependencies = [
        ("package", "0013_package_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="name"
            ),
        ),
        migrations.RunPython(forwards_func, reverse_func, elidable=True),
    ]
