# Generated by Django 2.2.20 on 2021-04-14 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0014_package_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='title',
        ),
    ]
