# Generated by Django 2.2.24 on 2021-09-20 09:19

from django.db import migrations
from users.models import MSP_WORKSPACE


def forwards_func(apps, schema_editor):
    """
    Fill the memberfield of a package
    """
    Package = apps.get_model("package", "Package")

    for package in Package.objects.all():

        if not package.member:
            if not package.project:
                continue
            # first lookup which member this could be based on workspace
            in_workspace = package.project.workspace
            if not package.created_by:
                # this was a job run by the system or early stage not registered
                # skip for now
                continue

            member_query = package.created_by.memberships.filter(
                object_uuid=in_workspace.uuid,
                object_type=MSP_WORKSPACE,
            )
            if member_query.exists():
                # get the membership out of it
                membership = member_query.first()
                if membership:
                    package.member = membership
            package.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("package", "0015_remove_package_title"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
