# Generated by Django 4.2.6 on 2023-10-19 09:33

import django.db.models.deletion
from django.db import migrations, models

from account.models.membership import MSP_WORKSPACE


def update_project_member(apps, schema_editor):
    Project = apps.get_model("project", "Project")  # noqa: N806
    for project in Project.objects.all():
        if project.created_by_user:
            membership = project.created_by_user.memberships.filter(
                object_uuid=project.workspace.uuid,
                object_type=MSP_WORKSPACE,
                deleted_at__isnull=True,
            ).first()
            if membership:
                project.created_by_member = membership
                project.save(update_fields=["created_by_member"])


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial_20230414"),
        ("project", "0001_initial_20230414"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="created_by",
            new_name="created_by_user",
        ),
        migrations.AddField(
            model_name="project",
            name="created_by_member",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="account.membership"),
        ),
        migrations.RunPython(update_project_member, reverse_code=migrations.RunPython.noop, elidable=True),
    ]
