# Generated by Django 3.2.15 on 2022-09-23 09:34

import uuid

import django.db.models.deletion
import django_cryptography.fields
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_alter_project_visibility_and_remove_unused_template"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="ProjectVariable",
                    fields=[
                        (
                            "created",
                            django_extensions.db.fields.CreationDateTimeField(
                                auto_now_add=True, verbose_name="created"
                            ),
                        ),
                        (
                            "modified",
                            django_extensions.db.fields.ModificationDateTimeField(
                                auto_now=True, verbose_name="modified"
                            ),
                        ),
                        ("deleted", models.DateTimeField(blank=True, null=True)),
                        (
                            "uuid",
                            models.UUIDField(
                                db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                            ),
                        ),
                        ("short_uuid", models.CharField(blank=True, max_length=32, unique=True)),
                        ("name", models.CharField(max_length=128)),
                        (
                            "value",
                            django_cryptography.fields.encrypt(models.TextField(blank=True, default=None, null=True)),
                        ),
                        ("is_masked", models.BooleanField(default=False)),
                        (
                            "project",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="variable",
                                to="project.project",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Project Variable",
                        "verbose_name_plural": "Project Variables",
                        "db_table": "project_variable",
                        "ordering": ["-created"],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
