# Generated by Django 3.2.15 on 2022-09-13 13:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0001_initial_squashed_20220901"),
    ]

    operations = []
