# Generated by Django 4.2.8 on 2023-12-28 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0002_alter_jobpayload_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobpayload",
            name="jobdef",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="job_payload", to="job.jobdef"
            ),
        ),
    ]
