# Generated by Django 4.2.8 on 2024-01-04 12:33

import core.utils.suuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0003_alter_jobpayload_jobdef"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobdef",
            name="suuid",
            field=models.CharField(
                default=core.utils.suuid.create_suuid, editable=False, max_length=32, unique=True, verbose_name="SUUID"
            ),
        ),
        migrations.AlterField(
            model_name="jobpayload",
            name="suuid",
            field=models.CharField(
                default=core.utils.suuid.create_suuid, editable=False, max_length=32, unique=True, verbose_name="SUUID"
            ),
        ),
        migrations.AlterField(
            model_name="runimage",
            name="suuid",
            field=models.CharField(
                default=core.utils.suuid.create_suuid, editable=False, max_length=32, unique=True, verbose_name="SUUID"
            ),
        ),
        migrations.AlterField(
            model_name="scheduledjob",
            name="suuid",
            field=models.CharField(
                default=core.utils.suuid.create_suuid, editable=False, max_length=32, unique=True, verbose_name="SUUID"
            ),
        ),
    ]
