# Generated by Django 3.2.15 on 2022-09-23 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0005_move_run_artifact"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="JobVariable",
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name="JobVariable",
                    table="project_variable",
                ),
            ],
        ),
    ]
