# Generated by Django 3.2.16 on 2022-12-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_remove_translation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdef',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='runimage',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
