# Generated by Django 3.2.16 on 2023-01-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_add_unique_together_to_run_image'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='jobdef',
            index=models.Index(fields=['name', 'created'], name='job_jobdef_name_986320_idx'),
        ),
    ]
