# Generated by Django 4.2.4 on 2023-08-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial_20230414"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="job_title",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="Job title"),
        ),
        migrations.AlterField(
            model_name="membership",
            name="object_type",
            field=models.CharField(choices=[("WS", "Workspace")], max_length=2),
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
