# Generated by Django 4.2.4 on 2023-09-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_move_avatar_files_to_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="object_type",
            field=models.CharField(
                choices=[
                    ("WS", "Workspace"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.CharField(
                choices=[
                    ("WV", "Workspace Viewer"),
                    ("WM", "Workspace Member"),
                    ("WA", "Workspace Admin"),
                ],
                default="WM",
                max_length=2,
            ),
        ),
    ]
