# Generated by Django 4.2.8 on 2024-01-04 12:33

import core.utils.suuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_alter_membership_object_type_alter_membership_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="suuid",
            field=models.CharField(
                default=core.utils.suuid.create_suuid, editable=False, max_length=32, unique=True, verbose_name="SUUID"
            ),
        ),
        migrations.AlterField(
            model_name="passwordresetlog",
            name="suuid",
            field=models.CharField(
                default=core.utils.suuid.create_suuid, editable=False, max_length=32, unique=True, verbose_name="SUUID"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="suuid",
            field=models.CharField(
                default=core.utils.suuid.create_suuid, editable=False, max_length=32, unique=True, verbose_name="SUUID"
            ),
        ),
    ]
