# Generated by Django 4.2.6 on 2023-10-19 09:33

import django.db.models.deletion
from django.db import migrations, models

from account.models.membership import MSP_WORKSPACE


def update_workspace_member(apps, schema_editor):
    Workspace = apps.get_model("workspace", "Workspace")  # noqa: N806
    for workspace in Workspace.objects.all():
        if workspace.created_by_user:
            membership = workspace.created_by_user.memberships.filter(
                object_uuid=workspace.uuid,
                object_type=MSP_WORKSPACE,
                deleted_at__isnull=True,
            ).first()
            if membership:
                workspace.created_by_member = membership
                workspace.save(update_fields=["created_by_member"])


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial_20230414"),
        ("workspace", "0001_initial_20230414"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workspace",
            old_name="created_by",
            new_name="created_by_user",
        ),
        migrations.AddField(
            model_name="workspace",
            name="created_by_member",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="account.membership"),
        ),
        migrations.RunPython(update_workspace_member, reverse_code=migrations.RunPython.noop, elidable=True),
    ]
