# Generated by Django 3.2.16 on 2022-12-22 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0007_description_do_not_allow_null_default_empty_string'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='activate_date',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='deactivate_date',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='status',
        ),
    ]
