# Generated by Django 4.2.6 on 2023-10-19 12:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("package", "0002_alter_package_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="package",
            old_name="created_by",
            new_name="created_by_user",
        ),
        migrations.RenameField(
            model_name="package",
            old_name="member",
            new_name="created_by_member",
        ),
    ]
