# Generated by Django 4.2.5 on 2023-09-29 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("package", "0003_update_package_created_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="package",
            old_name="description",
            new_name="archive_description",
        ),
        migrations.RenameField(
            model_name="package",
            old_name="original_filename",
            new_name="archive_filename",
        ),
        migrations.RenameField(
            model_name="package",
            old_name="created_by_member",
            new_name="archive_created_by_member",
        ),
        migrations.RenameField(
            model_name="package",
            old_name="size",
            new_name="archive_size",
        ),
        migrations.RenameField(
            model_name="package",
            old_name="created_by_user",
            new_name="archive_created_by_user",
        ),
        migrations.RenameField(
            model_name="package",
            old_name="finished_at",
            new_name="archive_finished_at",
        ),
        migrations.RemoveField(
            model_name="package",
            name="name",
        ),
        migrations.AlterField(
            model_name="package",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="packages", to="project.project"
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="archive_created_by_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="packages_archived_created_by_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="archive_size",
            field=models.IntegerField(default=None, help_text="Size of this package in bytes", null=True),
        ),
        migrations.DeleteModel(
            name="ChunkedPackagePart",
        ),
    ]
