#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

if [ -z "${POSTGRES_USER}" ]; then
    base_postgres_image_default_user='postgres'
    export POSTGRES_USER="${base_postgres_image_default_user}"
fi
export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

postgres_ready() {
python << END
import sys

import psycopg2

try:
    psycopg2.connect(
        dbname="${POSTGRES_DB}",
        user="${POSTGRES_USER}",
        password="${POSTGRES_PASSWORD}",
        host="${POSTGRES_HOST}",
        port="${POSTGRES_PORT}",
    )
except psycopg2.OperationalError:
    sys.exit(-1)
sys.exit(0)

END
}
until postgres_ready; do
  >&2 echo 'Waiting for PostgreSQL to become available...'
  sleep 1
done
>&2 echo 'PostgreSQL is available'


USER=django
GROUP=django
# Create django user and group if missing.
if ! id django
then
    # ----------------------------------------------------------------------------#
    # Make the django user have the same UID and GID as the owner of the
    # workdir. This avoids conflicts with owner/group for linux mounted volumes.
    # Mounted volumes on macOS ignore the owner/group, so this is safe there.
    # ----------------------------------------------------------------------------#
    # Create the django group, if possible with same GID as owner of
    # workdir.
    >&2 echo 'Creating django group'
    DIR_GID=$(stat -c '%g' .)
    addgroup -S -g $DIR_GID $GROUP || addgroup -S $GROUP
    # ----------------------------------------------------------------------------#
    # Create the django user, if possible with same UID as owner of
    # workdir.
    >&2 echo 'Creating django user'
    DIR_UID=$(stat -c '%u' .)
    adduser -S -u $DIR_UID -G $GROUP $USER || adduser -S -G $GROUP $USER
fi

# If the current owner of the workdir is root then it is not a mounted
# linux volume, which means changing the owner is safe as it will not
# propagate to the mounted volume from the host.
# Change owner of the workdir so that django can freely modify files
# under it if needed.
if [[ $(stat -c '%g' .) == 0 ]]
then
    >&2 echo 'Ensuring workdir ownership by django user'
    chown django:django .
    >&2 echo 'Ensuring storage_root ownership by django user'
    mkdir -p storage_root
    chown django:django storage_root
fi


# From: https://vitorbaptista.com/how-to-access-hosts-docker-socket-without-root
# Based on https://github.com/jenkinsci/docker/issues/196#issuecomment-179486312
# Altered to add django user to the group from /var/run/docker.sock
# Getting the groupname with stat -c "%G" /var/run/docker.sock
# Then add this group to the django user
DOCKER_SOCKET=/var/run/docker.sock
DOCKER_GROUP=docker
if [ -S ${DOCKER_SOCKET} ]; then
    FILE_GID=$(stat -c '%g' ${DOCKER_SOCKET})
    FILE_GNAME=$(stat -c '%G' ${DOCKER_SOCKET})

    # Create the group if it does not exists.
    if ! grep -q $FILE_GNAME /etc/group
    then
        >&2 echo 'Creating docker group'
        addgroup --gid ${FILE_GID} ${DOCKER_GROUP}
        FILE_GNAME=${DOCKER_GROUP}
    fi

    >&2 echo 'Adding django user to the docker group'
    addgroup django ${FILE_GNAME}
fi

echo "\$0 is '$0'"
echo "\$@ is '$@'"

# Execute the rest of the script with user django
su -s /bin/sh $USER -c "$@"
