#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset


python manage.py migrate
python manage.py loaddata fixtures/users.json
python manage.py loaddata fixtures/accounts.json
python manage.py loaddata fixtures/projects.json
python manage.py loaddata fixtures/jobdef.json

python manage.py collectstatic --noinput
/usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app
