# Generated by Django 3.2.16 on 2023-01-17 16:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_alter_membership_use_global_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name="UUID"),
        ),
    ]
