# Generated by Django 3.2.17 on 2023-02-22 14:05

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0008_alter_user_uuid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="membership",
            old_name="deleted",
            new_name="deleted_at",
        ),
        migrations.RenameField(
            model_name="membership",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="membership",
            old_name="modified",
            new_name="modified_at",
        ),
        migrations.RenameField(
            model_name="passwordresetlog",
            old_name="deleted",
            new_name="deleted_at",
        ),
        migrations.RenameField(
            model_name="passwordresetlog",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="passwordresetlog",
            old_name="modified",
            new_name="modified_at",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="deleted",
            new_name="deleted_at",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="modified",
            new_name="modified_at",
        ),
        migrations.AlterModelOptions(
            name="membership",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="passwordresetlog",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterUniqueTogether(
            name="membership",
            unique_together={("user", "object_uuid", "object_type", "deleted_at")},
        ),
        migrations.AlterField(
            model_name="membership",
            name="created_at",
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="membership",
            name="modified_at",
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="passwordresetlog",
            name="created_at",
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="passwordresetlog",
            name="modified_at",
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="modified_at",
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True),
        ),
    ]
