# Generated by Django 4.1.8 on 2023-04-14 14:43

import uuid

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import core.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account", "__first__"),
        ("job", "__first__"),
        ("package", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="UUID"
                    ),
                ),
                ("suuid", models.CharField(editable=False, max_length=32, unique=True, verbose_name="SUUID")),
                ("created_at", core.fields.CreationDateTimeField(auto_now_add=True)),
                ("modified_at", core.fields.ModificationDateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField(blank=True, default="")),
                ("name", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "SUBMITTED"),
                            ("PENDING", "PENDING"),
                            ("IN_PROGRESS", "IN_PROGRESS"),
                            ("COMPLETED", "COMPLETED"),
                            ("FAILED", "FAILED"),
                        ],
                        default="SUBMITTED",
                        max_length=20,
                    ),
                ),
                ("trigger", models.CharField(blank=True, default="API", max_length=20)),
                ("started_at", models.DateTimeField(editable=False, null=True)),
                ("finished_at", models.DateTimeField(editable=False, null=True)),
                (
                    "duration",
                    models.PositiveIntegerField(
                        blank=True, editable=False, help_text="Duration of the run in seconds", null=True
                    ),
                ),
                ("environment_name", models.CharField(default="", max_length=256)),
                ("timezone", models.CharField(default="UTC", max_length=256)),
                (
                    "celery_task_id",
                    models.CharField(blank=True, help_text="The task ID of the Celery run", max_length=120),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("jobdef", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="job.jobdef")),
                (
                    "member",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="account.membership"),
                ),
                (
                    "package",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="package.package"),
                ),
                (
                    "payload",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="job.jobpayload"
                    ),
                ),
                (
                    "run_image",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="job.runimage"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RunVariableRow",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="UUID"
                    ),
                ),
                ("suuid", models.CharField(editable=False, max_length=32, unique=True, verbose_name="SUUID")),
                ("modified_at", core.fields.ModificationDateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("project_suuid", models.CharField(db_index=True, editable=False, max_length=32)),
                ("job_suuid", models.CharField(db_index=True, editable=False, max_length=32)),
                ("run_suuid", models.CharField(db_index=True, editable=False, max_length=32)),
                (
                    "variable",
                    models.JSONField(default=None, editable=False, help_text="JSON field to store a variable"),
                ),
                ("is_masked", models.BooleanField(default=False)),
                (
                    "label",
                    models.JSONField(
                        default=None,
                        editable=False,
                        help_text="JSON field as list with multiple objects which are labels",
                    ),
                ),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="variables", to="run.run"
                    ),
                ),
            ],
            options={
                "db_table": "run_variable_row",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RunVariableMeta",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="UUID"
                    ),
                ),
                ("created_at", core.fields.CreationDateTimeField(auto_now_add=True)),
                ("modified_at", core.fields.ModificationDateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("count", models.PositiveIntegerField(default=0, editable=False, help_text="Count of variables")),
                (
                    "size",
                    models.PositiveIntegerField(default=0, editable=False, help_text="File size of variables JSON"),
                ),
                (
                    "variable_names",
                    models.JSONField(
                        blank=True,
                        default=None,
                        editable=False,
                        help_text="Unique variable names and data type for variable",
                        null=True,
                    ),
                ),
                (
                    "label_names",
                    models.JSONField(
                        blank=True,
                        default=None,
                        editable=False,
                        help_text="Unique variable label names and data type for variable label",
                        null=True,
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="variables_meta", to="run.run"
                    ),
                ),
            ],
            options={
                "db_table": "run_variable_meta",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RunResult",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="UUID"
                    ),
                ),
                ("suuid", models.CharField(editable=False, max_length=32, unique=True, verbose_name="SUUID")),
                ("created_at", core.fields.CreationDateTimeField(auto_now_add=True)),
                ("modified_at", core.fields.ModificationDateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "mime_type",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Storing the mime-type of the output file",
                        max_length=100,
                    ),
                ),
                (
                    "size",
                    models.PositiveIntegerField(default=0, editable=False, help_text="Size of the result stored"),
                ),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="result", to="run.run"
                    ),
                ),
            ],
            options={
                "db_table": "run_result",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RunMetricRow",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="UUID"
                    ),
                ),
                ("suuid", models.CharField(editable=False, max_length=32, unique=True, verbose_name="SUUID")),
                ("modified_at", core.fields.ModificationDateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("project_suuid", models.CharField(db_index=True, editable=False, max_length=32)),
                ("job_suuid", models.CharField(db_index=True, editable=False, max_length=32)),
                ("run_suuid", models.CharField(db_index=True, editable=False, max_length=32)),
                (
                    "metric",
                    models.JSONField(
                        default=None,
                        editable=False,
                        help_text="JSON field as list with multiple objects which are metrics, but we limit to one",
                    ),
                ),
                (
                    "label",
                    models.JSONField(
                        default=None,
                        editable=False,
                        help_text="JSON field as list with multiple objects which are labels",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="metrics", to="run.run"
                    ),
                ),
            ],
            options={
                "db_table": "run_metric_row",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RunMetricMeta",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="UUID"
                    ),
                ),
                ("created_at", core.fields.CreationDateTimeField(auto_now_add=True)),
                ("modified_at", core.fields.ModificationDateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("count", models.PositiveIntegerField(default=0, editable=False, help_text="Count of metrics")),
                (
                    "size",
                    models.PositiveIntegerField(default=0, editable=False, help_text="File size of metrics JSON"),
                ),
                (
                    "metric_names",
                    models.JSONField(
                        blank=True,
                        default=None,
                        editable=False,
                        help_text="Unique metric names and data type for metric",
                        null=True,
                    ),
                ),
                (
                    "label_names",
                    models.JSONField(
                        blank=True,
                        default=None,
                        editable=False,
                        help_text="Unique metric label names and data type for metric label",
                        null=True,
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="metrics_meta", to="run.run"
                    ),
                ),
            ],
            options={
                "db_table": "run_metric_meta",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RunLog",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="UUID"
                    ),
                ),
                ("suuid", models.CharField(editable=False, max_length=32, unique=True, verbose_name="SUUID")),
                ("created_at", core.fields.CreationDateTimeField(auto_now_add=True)),
                ("modified_at", core.fields.ModificationDateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("exit_code", models.IntegerField(default=0)),
                ("stdout", models.JSONField(blank=True, null=True)),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="output", to="run.run"
                    ),
                ),
            ],
            options={
                "db_table": "run_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RunArtifact",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="UUID"
                    ),
                ),
                ("suuid", models.CharField(editable=False, max_length=32, unique=True, verbose_name="SUUID")),
                ("created_at", core.fields.CreationDateTimeField(auto_now_add=True)),
                ("modified_at", core.fields.ModificationDateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("size", models.PositiveIntegerField(default=0, editable=False)),
                ("count_dir", models.PositiveIntegerField(default=0, editable=False)),
                ("count_files", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="artifact", to="run.run"
                    ),
                ),
            ],
            options={
                "db_table": "run_artifact",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChunkedRunResultPart",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="UUID"
                    ),
                ),
                ("suuid", models.CharField(editable=False, max_length=32, unique=True, verbose_name="SUUID")),
                ("created_at", core.fields.CreationDateTimeField(auto_now_add=True)),
                ("modified_at", core.fields.ModificationDateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("filename", models.CharField(max_length=500)),
                ("size", models.IntegerField(help_text="Size of this run result")),
                ("file_no", models.IntegerField()),
                ("is_last", models.BooleanField(default=False)),
                (
                    "runresult",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="run.runresult"
                    ),
                ),
            ],
            options={
                "verbose_name": "Run result chunk",
                "verbose_name_plural": "Run result chunks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChunkedRunArtifactPart",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="UUID"
                    ),
                ),
                ("suuid", models.CharField(editable=False, max_length=32, unique=True, verbose_name="SUUID")),
                ("created_at", core.fields.CreationDateTimeField(auto_now_add=True)),
                ("modified_at", core.fields.ModificationDateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("filename", models.CharField(max_length=500)),
                ("size", models.IntegerField(help_text="Size of this artifactchunk")),
                ("file_no", models.IntegerField()),
                ("is_last", models.BooleanField(default=False)),
                (
                    "artifact",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="run.runartifact"
                    ),
                ),
            ],
            options={
                "verbose_name": "Run artifact chunk",
                "verbose_name_plural": "Run artifacts chunks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="runvariablerow",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["variable"], name="runvariable_variable_json_idx", opclasses=["jsonb_path_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="runvariablerow",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["label"], name="runvariable_label_json_idx", opclasses=["jsonb_path_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="runmetricrow",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["metric"], name="runmetric_metric_json_idx", opclasses=["jsonb_path_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="runmetricrow",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["label"], name="runmetric_label_json_idx", opclasses=["jsonb_path_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="run",
            index=models.Index(fields=["name", "created_at"], name="run_run_name_4fdc9b_idx"),
        ),
    ]
