# Generated by Django 4.2.6 on 2023-10-19 12:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("run", "0001_initial_20230414"),
    ]

    operations = [
        migrations.RenameField(
            model_name="run",
            old_name="created_by",
            new_name="created_by_user",
        ),
        migrations.RenameField(
            model_name="run",
            old_name="member",
            new_name="created_by_member",
        ),
    ]
