# Generated by Django 4.2.7 on 2023-11-28 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0001_initial"),
        ("run", "0002_update_run_created_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="runartifact",
            options={"get_latest_by": "created_at", "ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="runartifact",
            name="size",
        ),
        migrations.RemoveField(
            model_name="runartifact",
            name="count_dir",
        ),
        migrations.RemoveField(
            model_name="runartifact",
            name="count_files",
        ),
        migrations.AlterField(
            model_name="runartifact",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="artifacts", to="run.run"
            ),
        ),
        migrations.DeleteModel(
            name="ChunkedRunArtifactPart",
        ),
    ]
