# Generated by Django 3.2.15 on 2022-09-23 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0006_move_run_artifact'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='runartifact',
            table='run_artifact',
        ),
    ]
