# Generated by Django 4.2.8 on 2024-01-03 15:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("run", "0007_move_run_payload_files_to_storage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="run",
            name="celery_task_id",
        ),
    ]
