# Generated by Django 4.2.8 on 2024-01-04 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("run", "0008_remove_run_celery_task_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="runvariablemeta",
            name="run",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="variables_meta", to="run.run"
            ),
        ),
    ]
