# Generated by Django 4.2.8 on 2024-01-04 12:33

import core.utils.suuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("run", "0009_alter_runvariablemeta_run"),
    ]

    operations = [
        migrations.AlterField(
            model_name="run",
            name="suuid",
            field=models.CharField(
                default=core.utils.suuid.create_suuid, editable=False, max_length=32, unique=True, verbose_name="SUUID"
            ),
        ),
        migrations.AlterField(
            model_name="runartifact",
            name="suuid",
            field=models.CharField(
                default=core.utils.suuid.create_suuid, editable=False, max_length=32, unique=True, verbose_name="SUUID"
            ),
        ),
        migrations.AlterField(
            model_name="runlog",
            name="suuid",
            field=models.CharField(
                default=core.utils.suuid.create_suuid, editable=False, max_length=32, unique=True, verbose_name="SUUID"
            ),
        ),
        migrations.AlterField(
            model_name="runmetricrow",
            name="suuid",
            field=models.CharField(
                default=core.utils.suuid.create_suuid, editable=False, max_length=32, unique=True, verbose_name="SUUID"
            ),
        ),
        migrations.AlterField(
            model_name="runresult",
            name="suuid",
            field=models.CharField(
                default=core.utils.suuid.create_suuid, editable=False, max_length=32, unique=True, verbose_name="SUUID"
            ),
        ),
        migrations.AlterField(
            model_name="runvariablerow",
            name="suuid",
            field=models.CharField(
                default=core.utils.suuid.create_suuid, editable=False, max_length=32, unique=True, verbose_name="SUUID"
            ),
        ),
    ]
