# Generated by Django 3.2.16 on 2022-11-03 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0012_rename_jobrun_to_run'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chunkedrunartifactpart',
            old_name='short_uuid',
            new_name='suuid',
        ),
        migrations.RenameField(
            model_name='chunkedrunresultpart',
            old_name='short_uuid',
            new_name='suuid',
        ),
        migrations.RenameField(
            model_name='run',
            old_name='short_uuid',
            new_name='suuid',
        ),
        migrations.RenameField(
            model_name='runartifact',
            old_name='short_uuid',
            new_name='suuid',
        ),
        migrations.RenameField(
            model_name='runlog',
            old_name='short_uuid',
            new_name='suuid',
        ),
        migrations.RenameField(
            model_name='runmetricrow',
            old_name='short_uuid',
            new_name='suuid',
        ),
        migrations.RenameField(
            model_name='runresult',
            old_name='short_uuid',
            new_name='suuid',
        ),
        migrations.RenameField(
            model_name='runvariablerow',
            old_name='short_uuid',
            new_name='suuid',
        ),
    ]
