# -*- coding: utf-8 -*-
import os

from django.db import models
from django.conf import settings

from core.fields import JSONField
from core.models import SlimBaseModel


class JobOutput(SlimBaseModel):
    """
    Includes the result and any other output generated by the job.
    """

    jobdef = models.UUIDField(blank=True, null=True, editable=False)
    jobrun = models.OneToOneField(
        "job.JobRun",
        on_delete=models.CASCADE,
        to_field="uuid",
        related_name="output",
    )
    exit_code = models.IntegerField(default=0)
    stdout = JSONField(blank=True, null=True)
    mime_type = models.CharField(
        max_length=100,
        blank=True,
        null=True,
        help_text="Storing the mime-type of the output file",
    )
    size = models.PositiveIntegerField(
        editable=False, default=0, help_text="Size of the result stored"
    )
    lines = models.PositiveIntegerField(
        editable=False, default=0, help_text="Number of lines in the result"
    )

    owner = models.CharField(max_length=100, blank=True, null=True)

    @property
    def stored_path(self):
        return os.path.join(
            settings.ARTIFACTS_ROOT, self.storage_location, self.filename
        )

    @property
    def storage_location(self):
        return os.path.join(
            self.jobrun.jobdef.project.uuid.hex,
            self.jobrun.jobdef.uuid.hex,
            self.jobrun.uuid.hex,
        )

    def __str__(self):
        return str(self.uuid)

    @property
    def filename(self):
        return "result_{}.output".format(self.uuid.hex)

    @property
    def read(self):
        """
        Read the result from filesystem and return
        """
        try:
            with open(self.stored_path, "rb") as f:
                return f.read()
        except FileNotFoundError:
            return b""

    def prune(self):
        pass
        # not implemented as file yet, the result is stored in the `stdout` field
        # os.remove(self.stored_path)

    class Meta:
        ordering = ["-created"]
        verbose_name = "Job Output"
        verbose_name_plural = "Job Outputs"


class ChunkedJobOutputPart(SlimBaseModel):
    filename = models.CharField(max_length=500)
    size = models.IntegerField(help_text="Size of this resultchunk")
    file_no = models.IntegerField()
    is_last = models.BooleanField(default=False)

    joboutput = models.ForeignKey(
        "job.JobOutput", on_delete=models.CASCADE, blank=True, null=True
    )

    class Meta:
        ordering = ["-created"]
