# Generated by Django 4.2.4 on 2023-08-18 06:21

import core.fields
from django.db import migrations, models
import django.db.models.deletion
import storage.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0004_add_objectreference"),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="UUID"
                    ),
                ),
                ("suuid", models.CharField(editable=False, max_length=32, unique=True, verbose_name="SUUID")),
                ("created_at", core.fields.CreationDateTimeField(auto_now_add=True)),
                ("modified_at", core.fields.ModificationDateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("file", models.FileField(upload_to=storage.models.get_upload_file_to)),
                (
                    "_created_by",
                    models.ForeignKey(
                        db_column="created_by",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_created_by",
                        to="core.objectreference",
                    ),
                ),
                (
                    "_created_for",
                    models.ForeignKey(
                        db_column="created_for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_created_for",
                        to="core.objectreference",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
