# Generated by Django 4.1.8 on 2023-04-14 15:17

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.fields


class Migration(migrations.Migration):
    replaces = [
        ("project", "0001_initial_squashed_20220901"),
        ("project", "0002_alter_project_visibility_and_remove_unused_template"),
        ("project", "0003_move_projectvariable"),
        ("project", "0004_alter_projectvariable_options"),
        ("project", "0005_rename_short_uuid_to_suuid"),
        ("project", "0006_uuid_and_suuid_field_config"),
        ("project", "0007_remove_translation"),
        ("project", "0008_alter_project_workspace"),
        ("project", "0009_description_do_not_allow_null_default_empty_string"),
        ("project", "0010_move_projectvariable"),
        ("project", "0011_auto_20221222_0720"),
        ("project", "0012_add_db_index"),
        ("project", "0013_add_at_suffix_to_datetime_fields"),
        ("project", "0014_move_field_to_core_iso_third_party_app"),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workspace", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="UUID"
                    ),
                ),
                ("suuid", models.CharField(editable=False, max_length=32, unique=True, verbose_name="SUUID")),
                ("created_at", core.fields.CreationDateTimeField(auto_now_add=True)),
                ("modified_at", core.fields.ModificationDateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField(blank=True, default="")),
                ("name", models.CharField(db_index=True, default="New project", max_length=255)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("PRIVATE", "PRIVATE"), ("PUBLIC", "PUBLIC")],
                        db_index=True,
                        default="PRIVATE",
                        max_length=10,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="workspace.workspace"),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["name", "created_at"], name="project_pro_name_b74a75_idx"),
        ),
    ]
