# Generated by Django 2.2.8 on 2020-08-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='template',
            field=models.UUIDField(db_index=True, editable=False, null=True),
        ),
    ]
