# Generated by Django 3.2.16 on 2022-11-03 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_projectvariable_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='short_uuid',
            new_name='suuid',
        ),
        migrations.RenameField(
            model_name='projectvariable',
            old_name='short_uuid',
            new_name='suuid',
        ),
    ]
