# Generated by Django 2.2.24 on 2021-07-05 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20210414_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workspace.Workspace'),
        ),
    ]
