# Generated by Django 3.2.16 on 2022-11-25 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0005_remove_translation"),
        ("project", "0007_remove_translation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="workspace",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="workspace.workspace"),
        ),
    ]
