# Generated by Django 3.2.16 on 2022-12-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_move_projectvariable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='activate_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='deactivate_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(db_index=True, default='New project', max_length=255),
        ),
    ]
