# Generated by Django 3.2.16 on 2023-01-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0011_auto_20221222_0720"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["name", "created"], name="project_pro_name_8c034f_idx"),
        ),
    ]
